### ISSUE TITLE
Jenny doesn't work in Unity + "Could not load file or assembly 'Entitas'"

### ISSUE THREAD

**Issue by Niek352** [sschmid/Entitas#1022]
I Try to use new entitas in Unity 
And Jenny Gen throw this exceptions

**To Reproduce**
1. Open project folder
2. dotnet Jenny.Generator.Cli "commands like: doctor, gen, fix"
3. And some errors thrown.

And if i try to gen from unity  i have this exception
1. Tools/Jenny/Generate
![image](https://user-images.githubusercontent.com/36474846/189310399-50141065-af3b-406f-ac97-d2a9fd935781.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36474846/189308716-750717ac-d566-45d0-bf9f-da52046cd4f4.png)

**Entitas Version**
 - Version 1.14.0

**Additional context**
Unity 2021.3.6f
Dotnet SDK updated to highest

On AssetStore version (1.12.3) all work correctly;

**Comment by sschmid** [comment]
Hi!
Regarding the first issue when generating in Unity:
Entitas 1.14.0 now comes with Roslyn code generators by default. For now this means: generate code using the terminal:
```
cd My/Project
dotnet Jenny/Jenny.Generator.Cli.dll gen
```

Running roslyn in Unity currently results in this issue.

The 2nd issue `Could not load file or assembly 'Entitas, Version=1.0.0.0` means that your Jenny.properties is not set up correctly and it doesn't know where to find Entitas.dll.

Please update the `Jenny.SearchPaths`, see [Match-One](https://github.com/sschmid/Match-One/blob/main/Jenny.properties)

**Comment by Niek352** [comment]
> Hi! Regarding the first issue when generating in Unity: Entitas 1.14.0 now comes with Roslyn code generators by default. For now this means: generate code using the terminal:
> 
> ```
> cd My/Project
> dotnet Jenny/Jenny.Generator.Cli.dll gen
> ```
> 
> Running roslyn in Unity currently results in this issue.
> 
> The 2nd issue `Could not load file or assembly 'Entitas, Version=1.0.0.0` means that your Jenny.properties is not set up correctly and it doesn't know where to find Entitas.dll.
> 
> Please update the `Jenny.SearchPaths`, see [Match-One](https://github.com/sschmid/Match-One/blob/main/Jenny.properties)

I already use Jenny.properties from Match-One,
Here is my properties and folder structure
![image](https://user-images.githubusercontent.com/36474846/189350206-42d6abe2-15bb-4a24-8e1e-7c00ff4988ad.png)
![image](https://user-images.githubusercontent.com/36474846/189350629-b77fe8ec-1dc3-4a9c-832c-d24b8f4b1811.png)

**Comment by sschmid** [comment]
Your `Jenny.Searchpaths` should point to `Assets/Entitas` so it can find `Entitas.dll`, see Match-One Jenny.properties, line 3 https://github.com/sschmid/Match-One/blob/main/Jenny.properties#L3

**Comment by sschmid** [comment]
I see you have Entitas in a `Plugins` subfolder, update your `Jenny.Searchpaths` accordingly

**Comment by sschmid** [comment]
e.g

```
Jenny.SearchPaths = Jenny/Plugins/Entitas, \
                    Jenny/Plugins/Jenny, \
                    Assets/Plugins/Entitas

```

**Comment by sschmid** [comment]
Explanation:

Jenny dynamically loads dll specified in `Jenny.Plugins`. It tries to find those by searching in all folders specified in `Jenny.SearchPaths`. Some plugins may have dependencies that will also be loaded, e.g. `Entitas.CodeGeneration.Plugins` depends on `Entitas`. In order to find all plugins + their dependencies you need to specify all paths in `Jenny.SearchPaths`

**Comment by Niek352** [comment]
Ok it finally work, thx
