### ISSUE TITLE
1.14 Jenny Generation causes compilation errors when the project is opened with Visual Studio for Mac

### ISSUE THREAD

**Issue by AlberGanAvi** [sschmid/Entitas#1035]
Jenny Generation causes compilation errors when the project is opened with Visual Studio for Mac

1. Open Match-One in a mac with Visual Studio for Mac
2. Generate with dotnet Jenny/Jenny.Generator.Cli.dll gen
3. Go to Unity and see that there are compilation errors about duplicated and missing classes

**Expected behavior**
No compilation errors after code generation

**Screenshots**
![Captura de pantalla 2022-09-25 a las 0 10 58](https://user-images.githubusercontent.com/114394013/192457318-9a860f9f-710b-4349-98dd-d7677f005d18.png)
![Captura de pantalla 2022-09-24 a las 10 17 07](https://user-images.githubusercontent.com/114394013/192457351-d1c3482f-916a-4824-b7d3-15a6349a2c5c.png)

**Entitas Version**
 - Version Entitas 1.14

**Additional context**
I think it happens with Visual Studio for Mac and with Visual Studio Code but for sure not with Rider

Zip with the project
The zip contains all the project files after opening it with Visual Studio for Mac and after Jenny Generation was executed so it has compilation errors. Also, I had to remove the Library folder because with it the zip was too big to update to GitHub issues.
[Match-One_IDE_VisualStudioForMac_GeneratedBroken 2.zip](https://github.com/sschmid/Entitas/files/9652625/Match-One_IDE_VisualStudioForMac_GeneratedBroken.2.zip)

**Comment by sschmid** [comment]
@AlberGanAvi I can confirm and reproduce.
Unity generates a different csproj file depending on Rider or VS code, which I find surprising. The Roslyn code generator plugin uses standard practices and no special customization, so the VS code produced csproj seems off. I will investigate and check the differences.

**Comment by sschmid** [comment]
Among other things, this is missing when not using Rider. Adding those fixes the issue for me. Unfortunately, those lines will be removed when csproj is regenerated. Will investigate more
```
<_TargetFrameworkDirectories>non_empty_path_generated_by_unity.rider.package</_TargetFrameworkDirectories>
<_FullFrameworkReferenceAssemblyPaths>non_empty_path_generated_by_unity.rider.package</_FullFrameworkReferenceAssemblyPaths>
<DisableHandlePackageFileConflicts>true</DisableHandlePackageFileConflicts>
```

**Comment by sschmid** [comment]
Will fix using a Jenny PreProcessor

**Comment by sschmid** [comment]
Fixed in `Jenny.Plugins` 1.1.0

Reattached new `Jenny.zip` to Entitas 1.14.1
https://github.com/sschmid/Entitas/releases/tag/1.14.1

You can add a new pre processor `Jenny.Plugins.ReferenceAssemblyPathsPreProcessor` to Jenny.properties like in Match-One
https://github.com/sschmid/Match-One/commit/ad34a99ba17e8cd95b698e21384bd7292bc2e5ff
