### ISSUE TITLE
The ability to name entities

### ISSUE THREAD

**Issue by Discipol** [sschmid/Entitas#1038]
Right now I made a NameComponent to store the name but it feels like CreateEntity( "ABC) and entity.name = "ABC" should be a default behavior.

**Comment by sschmid** [comment]
Creating a `NameComponent` as you mentioned sounds good. This way you could also use it to get entities by name with an EntityIndex.
I don't think having a name should be default behaviour on an entity. It increases the size of the entity if you are using the name or not.

Will close for now, but please feel free to reopen if I'm missing something!
