### ISSUE TITLE
Cannot generate with dotnet on a mac  (dotnet 6 and Entitas 1.14.1)

### ISSUE THREAD

**Issue by eatsports** [sschmid/Entitas#1043]
Hey, i cant seem to generate code with dotnet on a mac :(
Here's the console, it works fine on windows
After googling it seems like it might be a dotnet issue, but maybe there is a known fix already
![image](https://user-images.githubusercontent.com/29803390/196757872-39cb92a6-1773-4440-afe6-0b23fefbfb96.png)

**Comment by sschmid** [comment]
@eatsports Hi, can you please check your dotnet version

```
dotnet --version
```

Must be 6.0.0 or higher

**Comment by eatsports** [comment]
Yeah, its the first thing i checked, im on 6.0.402

**Comment by eatsports** [comment]
![image](https://user-images.githubusercontent.com/29803390/197199209-85dec529-f8c3-47d3-ae70-7ac7561602b9.png)

**Comment by woshihuo12** [comment]
meet same issue.

**Comment by woshihuo12** [comment]
> Yeah, its the first thing i checked, im on 6.0.402

are you solve this bug?

**Comment by woshihuo12** [comment]
@sschmid 
1.14.0 not has this bug.
so 1.14.1 introduce this bug.

**Comment by woshihuo12** [comment]
when i replace the 1.4.1 plugin's Microsoft.Build.Locator.dll file with 1.4.0. the error will be disappear.
