### ISSUE TITLE
Version 1.14.1 ./Jenny/Jenny: No such file or directory

### ISSUE THREAD

**Issue by EvgenL** [sschmid/Entitas#1047]
**Describe the bug**
Version 1.14.1 doesn't contain Jenny executable

**To Reproduce**

1. Create unity project in version 2021.3.12f1
2. Download Entitas.zip and Jenny.zip from Releases page
3. Put contents of Entitas.zip in Assets/Plugins in unity project
4. Put contents of Jenny.zip in ~~Assets/ in unity project~~ root project folder
5. In Unity click Assets/Open C# project to generate project
6. Click Tools/Jenny/Preferences -> Auto Import -> Continue and Overwrite
7. Click Jenny -> Generate. Get "Generated 0 files (0 sloc, 0 loc)"
8. In macos terminal go to ...../Assets
9. Run ./Jenny-Auto-Import.
10. Get this: 
`/Users/***/EntitasTest/Jenny-Auto-Import: line 4: ./Jenny/Jenny: No such file or directory
/Users/***/EntitasTest/Jenny-Auto-Import: line 5: ./Jenny/Jenny: No such file or directory
Press any key to continue
`
**Expected behavior**
Jenny-Auto-Import should work

**Comment by sschmid** [comment]
@EvgenL Jenny.zip should be extracted into your project folder, outside of the Assets folder.
Example folder structure: Match-One
https://github.com/sschmid/Match-One

**Comment by EvgenL** [comment]
@sschmid That is exactly what I did. Sorry, I made a mistake in initial post.

**Comment by andreylitvintsev** [comment]
The same situation. I spent whole day to try fix it. Yes, I compared with "Match-One". Generator work only from command line: `dotnet Jenny/Jenny.Generator.Cli.dll gen`.

**Comment by sschmid** [comment]
Yes, due to upgrading to .NET 6.0, the roslyn code generator plugins only work in the terminal.
Using the terminal with jenny server is the recommended way and is also the fastest way to generate

start server in terminal
```
dotnet Jenny/Jenny.Generator.Cli.dll server
``` 

Use rider run configs, another terminal, or Unity menu item (generate using server)
```
dotnet Jenny/Jenny.Generator.Cli.dll client gen
```

**Comment by Stovoy** [comment]
Yeah, just need to update the scripts in the Jenny.zip root folder for the release :) as the current ones do not work anymore.

**Comment by sschmid** [comment]
🙈 you're right, they are not updated, will do!

**Comment by sschmid** [comment]
I updated the scripts for Match one. Next Entitas release will include fixed convenience scripts in the zip file.
