### ISSUE TITLE
ContextObserverGenerator Generate fail

### ISSUE THREAD

**Issue by RouderSky** [sschmid/Entitas#1049]
![image](https://user-images.githubusercontent.com/18010177/204140726-99505dd8-fdd2-4ab9-8eb7-f908ff7786f9.png)

![image](https://user-images.githubusercontent.com/18010177/204103738-5d0eda8a-2b37-4c2f-a0d2-648824a82520.png)
![image](https://user-images.githubusercontent.com/18010177/204103776-5cfeede2-5d3a-44dd-9acd-2ac46e5c6443.png)
it should like this
![image](https://user-images.githubusercontent.com/18010177/204103830-7b72bd0c-8424-44a1-a9b5-1356ab4e02bc.png)
but why this?
![image](https://user-images.githubusercontent.com/18010177/204103730-71e4edea-c4fa-4dd6-aebd-99c0f14cba10.png)

**Comment by sschmid** [comment]
I would guess that the Jenny.properties is not setup correctly.
You can run the doctor to check if there any issues

```
.\Jenny Jenny.exe doctor
```
