### ISSUE TITLE
Need help with Roslyn

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas#1051]
# Need help with Roslyn

I'm stuck on a roslyn issue and need help.

### Setup:

I want to get the `ContextAttribute` from a component using Roslyn, e.g.
- Context("Test1")
- Context("Test2")

```csharp
using Entitas;
using Entitas.Plugins.Attributes;

namespace My.Namespace
{
    [Context("Test1"), Context("Test2")]
    public sealed class MyComponent : IComponent
    {
        public string Value;
    }
}
```

### Problem:

The `ContextAttribute` is not recognized.

I created a branch with a failing unit test to reproduce and help debugging:
- branch: [roslyn-attributes](https://github.com/sschmid/Entitas/tree/roslyn-attributes)
- test: [AttributesTests.TestFixtures()](https://github.com/sschmid/Entitas/blob/roslyn-attributes/tests/Entitas.Plugins.Tests/AttributesTests.cs)

### More info

- The unit test fails and the attribute is `Entitas.Context` instead of `Entitas.Plugins.Attributes.ContextAttribute("Test1")`
- The `AttributeClass` is `ExtendendErrorTypeSymbol` instead of `NonErrorTypedSymbol`
- Even System attributes like `System.Obsolete` is not recognized
- I could fix System attributes by manually adding `MetadataReference`, but could not fix the Entitas attributes

```csharp
project = project.AddMetadataReference(MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location))
    .AddMetadataReference(MetadataReference.CreateFromFile(Path.Combine(ProjectPath, "bin", "Release", "Entitas.dll")))
    .AddMetadataReference(MetadataReference.CreateFromFile(Path.Combine(ProjectPath, "bin", "Release", "Entitas.Plugins.Attributes.dll")));
```

- When compiling the code generator and running it on the test fixtures project, everything works as expected. Only the unit tests are failing?!
- For sanity reasons, I added a test pointing to the Match-One project where I modified the `AssetComponent` similar to the test component, and the test passes.

```csharp
using System;
using Entitas;
using Entitas.Plugins.Attributes;

[Game, Context("Test"), Obsolete("My Reason")]
public sealed class AssetComponent : IComponent
{
    public string Value;
}
```

### Summary:

- Code Generator itself works
- Only unit test fails (?!?)
- Tests work on Match One (old style csproj)
- Tests fail on Test Fixtures (sdk style csproj) and symbols are not resolved correctly

Do I need to manually add more project or assembly references?
Am I loading the project wrong?
Do I somehow run the unit test in a different way as the code generator?

Any help is appreciated!

**Comment by sschmid** [comment]
I extracted the affected code to a minimal standalone setup that can be tested easily:

https://github.com/sschmid/RoslynUnitTestIssue

**Comment by xtqqksszml** [comment]
Hi, sschmid. I'm stuck on a roslyn issue too. 
I was run all tests with Entitas-1.14.2, and I got several errors in Entitas.CodeGeneration.Tests.  you can see the picture. 
Is this the same problem as yours? Were you fixed it?
![image](https://user-images.githubusercontent.com/8028068/207267543-276c1ddb-377b-423c-9e8b-87611aa926e5.png)

**Comment by sschmid** [comment]
@xtqqksszml yes, that's exactly the issue. Those fail for me too.

I recreated the issue in the minimal project setup mentioned above:
https://github.com/sschmid/RoslynUnitTestIssue

Still not sure how to fix it... any help is appreciated

**Comment by sschmid** [comment]
Solved by adding `NuGet.Frameworks` package to the test project

https://github.com/sschmid/RoslynUnitTestIssue/issues/1#issuecomment-1348083201

https://github.com/dotnet/roslyn/issues/52954

**Comment by xtqqksszml** [comment]
@sschmid Thank you. I just tried it again, and It was solved.
