### ISSUE TITLE
Does Entitas support Unreal?

### ISSUE THREAD

**Issue by Icekettle** [sschmid/Entitas#1054]
Hi,
   I can not find any doc or example for unreal, does it mean Entitas doesn't support unreal?

**Comment by vakuor** [comment]
Check main page of Entitas.
![image](https://user-images.githubusercontent.com/19931959/222764713-09bf131e-9742-40db-960d-86003041174e.png)
https://github.com/JuDelCo/Entitas-Cpp

**Comment by sschmid** [comment]
@Icekettle Entitas itself is engine agnostic and can work everywhere where C# is supported.

**Comment by Icekettle** [comment]
> Check main page of Entitas. https://github.com/JuDelCo/Entitas-Cpp ![image](https://user-images.githubusercontent.com/19931959/222764713-09bf131e-9742-40db-960d-86003041174e.png)

Yes, I knew this, thanks. But it seems it doesn't keep update.

**Comment by Icekettle** [comment]
> @Icekettle Entitas itself is engine agnostic and can work everywhere where C# is supported.

Got it, thank you very much!
