### ISSUE TITLE
【Entitas1.14.1】jenny auto import，not contexts

### ISSUE THREAD

**Issue by sugtex** [sschmid/Entitas#1061]
I followed the steps on the document and after importing, the automatic import did not appear contexts。

![84AI@I%9~XW1LFS$3UDGW{5](https://user-images.githubusercontent.com/52211149/229883125-27242a82-64fd-4952-aa1f-8911f6d4e636.png)

**Comment by sugtex** [comment]
Normal should be like this？

![image](https://user-images.githubusercontent.com/52211149/229883625-dffb7b8c-47a9-4195-875e-599898bf1ed3.png)

**Comment by sugtex** [comment]
Normal should be like this？
![image](https://user-images.githubusercontent.com/52211149/229883774-e6a34721-c78b-45bd-8adb-a7129a26214c.png)

**Comment by PixStudioPL** [comment]
Got the same with unity 2022.2 :(

**Comment by PopSlime** [comment]
For some reason I got it working by importing twice. Just run `dotnet Jenny.Generator.Cli.dll` again.

**Comment by TrungNVX** [comment]
> For some reason I got it working by importing twice. Just run `dotnet Jenny.Generator.Cli.dll` again.

How to run this, plese help me. I am new to UnityDev

**Comment by TrungNVXBraveStars** [comment]
> Normal should be like this？ ![image](https://user-images.githubusercontent.com/52211149/229883774-e6a34721-c78b-45bd-8adb-a7129a26214c.png)
Hope this reply is not too late. You should download 2 file named Jenny and Entitas from github: https://github.com/sschmid/Entitas/releases/tag/1.14.1
Create your project, and create an arbitrary C# script to generate an Assembly-CSharp file. Comback to Unity, open Tool/Jenny/Preferences, click auto import and override. Click Edit Jenny.Properties, it will open a path file and copy things from this link (Match-One game): https://github.com/sschmid/Match-One/blob/main/Jenny.properties. Save this file and now you can create components, generate code using the command "dotnet Jenny.Generator.Cli.dll gen".
Hope you find it well.

**Comment by sugtex** [comment]
Thanks for your help！
