### ISSUE TITLE
broken doc link

### ISSUE THREAD

**Issue by fuyaozs9wl** [sschmid/Entitas#1062]
**broken doc link**
how 2 find a full doc?
![图片](https://user-images.githubusercontent.com/132030377/236256564-f1336df0-cfb7-44e3-b32e-a72d4c9f9ba2.png)

**Comment by sschmid** [comment]
I removed the auto-generated doxygen docs (Entitas API reference) in 1.14.0.

Tag 1.13.0 contains it https://github.com/sschmid/Entitas/tree/1.13.0/docs

**Comment by sschmid** [comment]
duplicate #1044
