### ISSUE TITLE
EntityIsAlreadyRetainedByOwnerException

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas#468]
I'm still learning Entitas so I'm not sure what I did to cause this or what information will help, so bear with me.

I have a ReactiveSystem, UpdateContainerViewSystem which might be a little wierdly setup, but essentially its job is to react to one of two things: Either the active(focused) container has changed, or an entity has moved to another container (containerLocation). 

When it executes its job is get the currently focused container entity, which is done by a Unique flag component, then get its ID, and finally get all entities that say this container ID is its location, which is handled by an EntityIndex attribute.

The code:
```csharp
using System;
using Entitas;
using System.Collections.Generic;
using UnityEngine;

namespace Source.Systems
{
    public class UpdateContainerViewSystem : ReactiveSystem<GameEntity>
    {
        readonly GameContext context;

        public UpdateContainerViewSystem(Contexts contexts) : base(contexts.game) 
        {
            context = contexts.game;
        }

        protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
        {
            // specify which component you are reacting to
            return context.CreateCollector(GameMatcher.AnyOf(GameMatcher.ContainerLocation, GameMatcher.FocusedContainer));
        }

        protected override bool Filter(GameEntity entity)
        {
            return entity.hasContainerLocation;
        }

        protected override void Execute(List<GameEntity> entities)
        {
            GameEntity focusedContainer = context.focusedContainerEntity;
            List<GameEntity> itemsInContainer = new List<GameEntity>(context.GetEntitiesWithContainerLocation(focusedContainer.iD.value));
            focusedContainer.containerViewListener.listener.ContainerViewChanged(itemsInContainer);
        }
    }
}
```

However, as soon as an Entity gets a containerLocation component added, AND its value is set to a container (whether that container is focused or not), the log starts spamming:

```
EntityIsAlreadyRetainedByOwnerException: 'ReactiveSystem(UpdateContainerViewSystem)' cannot retain Entity_3(*8)(ContainerLocation, ID)!
Entity is already retained by this object!
The entity must be released by this object first.
Entitas.SafeAERC.Retain (System.Object owner)
Entitas.Entity.Retain (System.Object owner)
Entitas.ReactiveSystem`1[TEntity].Execute ()
Entitas.VisualDebugging.Unity.DebugSystems.StepExecute ()
Entitas.VisualDebugging.Unity.DebugSystems.Execute ()
Entitas.VisualDebugging.Unity.DebugSystems.StepExecute ()
Entitas.VisualDebugging.Unity.DebugSystems.Execute ()
GameController.Update () (at Assets/Source/Unity/GameController.cs:36)
```

**Comment by jwvanderbeck** [comment]
Changing things to use a ExecuteSystem works as expected, so it appears the issue does have to do with the funky way I am using the ReactiveSystem.

Is there a better way to handle this? Basically I only want to react to changes in the ContainerLocationComponent, but when I react to that I am working with a different entity than the ones that have that component, so the ReactiveSystem setup ends up a bit odd.

**Comment by sschmid** [comment]
Hi, I saw you're using AnyOf in the trigger. Usually I'm alarmed when seeing this, because mots of the time you want to use a MultiReactiveSystem, because you want to react when either .ContainerLocation or FocusedContainer changed.
Try this:

```
    protected override Collector<GameEntity> GetTrigger(IContext<GameEntity> context) {
        return new Collector<GameEntity>(
            new [] {
                context.GetGroup(GameMatcher.ContainerLocation),
                context.GetGroup(GameMatcher.FocusedContainer)
            },
            new [] {
                GroupEvent.Added,
                GroupEvent.Added
            }
        );
    }
```

**Comment by jwvanderbeck** [comment]
@sschmid No, Maxim mentioned the same thing and this has/had nothing to do with it as far as I can tell.  Even after changing to use that system the problem still occurred.

It seems to be an issue with the filter being "too loose" if that makes any sense, that causes the execute to get called to quickly back to back, perhaps before one execution has even finished? I'm not sure.

I re-factored things several times and constantly kept fixing the bug and then running right back into it and it was extremely frustrating because I had no idea what the root cause of such an error was or where to even look to try and fix it.

Right now it is currently working so I'm afraid to touch it at all, but not understanding what the error is or why it was being caused bothers me.

**Comment by sschmid** [comment]
I checked your code now and I don't see anything suspicious.
The error can only appear if:
1.
you're executing the system again while the first execute hasn't finished yet, e.g. as a result of `focusedContainer.containerViewListener.listener.ContainerViewChanged` you call system.Execute() again (I hope you don't :))
2.
something fails quietly and the execute didn't properly finish, which prevents the system to properly release the entities

**Comment by sschmid** [comment]
If none of these 2 descriptions apply to your code, I'd be interested in a small test case to reproduce.

**Comment by sschmid** [comment]
Is this still relevant, otherwise feel free to close
