### ISSUE TITLE
ECS cookbook?

### ISSUE THREAD

**Issue by fayte0618** [sschmid/Entitas#484]
I'm a beginner when it comes to ECS architecture and it would really help if there were people kind enough to share their techniques or common patterns in ECS framework (like multiple features sharing the same component, handling Game objects with multiple heirarchies etc.)

**Comment by BenjaBobs** [comment]
@mzaks Has created [this](https://github.com/mzaks/EntitasCookBook/tree/master/chapters) all though it's not complete yet.

**Comment by IsaiahKelly** [comment]
We do have a FAQ in the wiki which can serve a similar purpose, but why is that cookbook a separate repository instead of a part of the wiki? The official wiki seems like a much better, more visible and much more easily editable place for this type of content.

**Comment by nbreum15** [comment]
Having read it all, it would awesome if he continues writing it. It would be awesome to have a book that goes more in depth with ECS as there aren't any book (that i could find) written solely for it.

**Comment by mzaks** [comment]
Yeah, yeah, I just wrote another two chapters. Sorry for being so slow, it's just a side project so I return too it only when being kicked 😀. Keep kicking me, other wise I will digress into doing some other things 😅.
