### ISSUE TITLE
Generate randomly opens Paypal, Chat or Wiki

### ISSUE THREAD

**Issue by zendorx** [sschmid/Entitas#509]
Hi,

I got redirected to paypal for entitas donation while pressing "generate". Is that really so necessary functionality? It's looks like some sort of malware, it's not good at all.

Cheers

**Comment by sschmid** [comment]
Hi, that is definitely not implemented like this, but sound like a good idea :)
Are you sure you didn't accidentally hit the donate button in the top right of the window?

[Generate Button](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Unity.Editor/Entitas.CodeGeneration.Unity.Editor/Editor/CodeGeneratorPreferencesDrawer.cs#L141-L143) only ever generates. There's no hidden functionality to make people donate. While donations are appreciated, there are no cheesy tricks implemented from my side to end up on this website.

**Comment by zendorx** [comment]
Yes, i'm sure. I use ctrl+shift+g shortcut. There no way I could press anything else. Do you have hotkeys for donate? :)

**Comment by KumoKairo** [comment]
I also get redirected to a donation page randomly when trying to generate with Ctrl + Shift + G from the Unity editor. Always thought I misclicked something. Doesn't happen often, but sometimes pops up

**Comment by sschmid** [comment]
That is impossible, you can check the code. No hotkeys, no hidden functionality...
This is the one and only code path that calls donate
https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.Unity.Editor/Entitas.Unity.Editor/Editor/GUI/PreferencesWindow.cs#L74

**Comment by sschmid** [comment]
Still sounds like a good idea though ;)

**Comment by sschmid** [comment]
But on the other side I'm a little bit confused now how this can happen. Of course I use the same release than everyone else, for years, it never happened to me or any other collegue, and judging from the code, that is impossible.

**Comment by sschmid** [comment]
Calling out Unity on this one, and on top of that I make a guess and say you're both on windows ;)

**Comment by zendorx** [comment]
https://github.com/sschmid/Entitas-CSharp/blob/22757c60dd96a2722091253715b9531dfb88b879/Addons/Entitas.CodeGeneration.CodeGenerator.CLI/Commands/Donate.cs

**Comment by sschmid** [comment]
:) yes, an easter egg for people who actually read the code - congrats. Go ahead and try the command, it will blow your mind :)

**Comment by zendorx** [comment]
for printing heart? :)

**Comment by sschmid** [comment]
✨✨✨

**Comment by zendorx** [comment]
Yes, i'm on Windows.

**Comment by sschmid** [comment]
Windows - where the magic happens :)

Ok, I'll close. I showed you the code. It's open source, I couldn't hide sneaky tricks like that even if I wanted to :) You can verify yourself in the link I posted that it is impossible other than Unity on Windows has issues with custom menu items.

**Comment by sschmid** [comment]
... buuut still sounds like a good idea to do so :) haha

**Comment by KumoKairo** [comment]
![image](https://user-images.githubusercontent.com/2943071/33744497-78566fda-dbc2-11e7-9a02-b0079199b1d9.png)

**Comment by FNGgames** [comment]
This happens to me a lot too, never said anything before - ctrl-shift-g sometimes opens the chat, the wiki, or the donate page instead of generating.

**Comment by kdrzymala** [comment]
Yeah, saw that too :)
Thought it's by design ;-)

**Comment by sschmid** [comment]
Re-opening, because more people saw this happen. I redirect you to Unity Support
https://support.unity3d.com/where you can file a bug.

As far as I can judge, it's either a Unity bug or a Windows bug. Again, Entitas itself never actually goes those code paths as you can verify yourself.

**Comment by FNGgames** [comment]
It's really unpredictable when it happens, sometimes I have a whole session with multiple generates and it doesn't happen, sometimes it seems to happen every time i jump back to unity to generate. ¯\_(ツ)_/¯

**Comment by ShadeSlider** [comment]
I thought it was intended as well =)
50% of the time hitting Ctrl+Shift+G opens a donation page for me as well =)
I actually have a reflex to hit Ctrl+W => Alt+Tab right after hitting generate hotkey now :)

**Comment by sschmid** [comment]
That's so weird. I hope one of you guys did tell Unity already :)

**Comment by jwvanderbeck** [comment]
I've seen this before as well and I don't see how you can call it a Unity bug if it is directing us to Entitas specific stuff.

I also agree the code looks clean but doesn't change the fact that I've seen it once or twice!

**Comment by sschmid** [comment]
@jwvanderbeck I might be wrong, but I call it a Unity bug because of 2 reasons:
1. The code path is very simple and clear and is only using Unity APIs as recommended (afaik) but the result is different and random on Windows
2. Teams (on Macs) have been using Entitas for the last 4 years and it never appeared

But of course, I'd love to hear if I'm wrong, because only then I can do sth about it.
