### ISSUE TITLE
Create Nuget Package for Entitas

### ISSUE THREAD

**Issue by aaronmell** [sschmid/Entitas#52]
I really like your tool, I just wish it was a nuget package that I could consume rather than download the src and add files to my project.

**Comment by sschmid** [comment]
Thanks! Makes sense, I'll see what I can do ;)

**Comment by aaronmell** [comment]
In order for this to work, I believe your going to have to remove the reliance on partial classes during generation. Since a partial cannot exist outside of the assembly it wouldn't work in its current form.

**Comment by sschmid** [comment]
That's true, the package would have to contain the source files.

**Comment by aloisdeniel** [comment]
Would be very interested in that too!

I haven't used Entitas (and I won't with Unity) yet, but couldn't a inherited class could be generated ?

```csharp
   public class Entity : Entitas.Entity {
        #region Components
        #region Position
        public PositionComponent position { get { /* ... */ } }
        public bool hasPosition { get {  /* ... */ } }
        public Entity AddPosition(float newX, float newY) { /* ... */ }
        public Entity ReplacePosition(float newX, float newY) { /* ... */ }
        public Entity RemovePosition() { /* ... */  }
        #endregion
        #region Rotation
        public RotationComponent position { get { /* ... */ } }
        public bool hasPosition { get {  /* ... */ } }
        public Entity AddPosition(float angle) { /* ... */ }
        public Entity ReplacePosition(float angle) { /* ... */ }
        public Entity RemovePosition() { /* ... */  }
        #endregion
        #endregion
    }
```

**Comment by sschmid** [comment]
Update:
Just released 0.41.0 which now deploys Entitas as Dlls instead of source code. The code generator doesn't rely on partial classes anymore.
It's now possible to easily create nuget packages with the c# only version.

**Comment by haggerty-william** [comment]
Was a nuget package ever created? Cant seem to find an official nuget package.

**Comment by sschmid** [comment]
No, there's no nuget package for Entitas

**Comment by hiradyazdan** [comment]
@sschmid Will there be a nuget package at some point, or it is no longer planned?
