### ISSUE TITLE
Alternative asset store download

### ISSUE THREAD

**Issue by WoLfulus** [sschmid/Entitas#562]
Hello,

I saw some asset creators that integrates some kind of unity APIs on their websites, which allows putting the order number and downloading the most updated version of the asset. Could this be done for entitas?

I really don't wanna copy releases from github inside the project and sometimes messing things up. Also, asset store has updated roslyn plugins too, has the unitypackage ready to be installed and stuff, which github releases doesn't.

Does it makes sense? 

Maybe this could help with some kind of "autoupdate" too.

**Comment by sschmid** [comment]
Not quite sure what you mean. Do you have an example of websites using Unity apis?

Would a unitypackage attached to a release help already?

**Comment by sschmid** [comment]
roslyn is asset store only

**Comment by WoLfulus** [comment]
Thats why I'm asking for this :( 

Anyways, I couldn't find the publisher that has the feature, but I found the API request

http://api.assetstore.unity3d.com/api-docs/#!/invoice/verifyInvoice_get_0

**Comment by AVAVT** [comment]
I second the idea. This way instead of having to wait 2-4 days for asset store update, purchasers can enter their invoice and download the latest release immediately.

**Comment by sdarkwell** [comment]
I agree. If possible, I would also appreciate this enhancement.

One example of an asset developer who has implemented a system like this is Guavaman Enterprises with their Unity input asset Rewired. See:  [http://guavaman.com/rewired/latest]. After entering your Email address and invoice number, clicking "Download" automatically serves up the newest Unity asset package for the full version of Rewired.

It would be a nice benefit of those who have paid to support Entitas, instead of feeling like we are missing out the benefit of your efforts to quickly patch any issues.

- S.

**Comment by WoLfulus** [comment]
I could even write the whole system myself. Just give me a green sign that it will actually be used and consider done.

**Comment by WoLfulus** [comment]
Here's an example

https://ludiq.io/build/924

**Comment by sschmid** [comment]
@WoLfulus How would you do this?

**Comment by WoLfulus** [comment]
Simple download script that pre-signs an Amazon S3 download url (and binds it to the download button) just after checking if the order number is valid via Unity API.

**Comment by denizdikbiyik** [comment]
Hello,
If you want to find an alternative for asset store because you cannot find your material, you can try to find 2D images or create them and by using designing programs, you can give third dimension to it as depth.
This may help.

**Comment by denizdikbiyik** [comment]
Hello,
I also noticed that there is a very good website for 3D models and I want to share it with you:
https://www.turbosquid.com/

And there is an option that if you cannot find 3D models you need, you can draw them on SketchUp.

**Comment by sschmid** [comment]
ref #992
