### ISSUE TITLE
Different generate result between Unity and Roslyn

### ISSUE THREAD

**Issue by CuiXiaoliang** [sschmid/Entitas#567]
Hi,I am new to Entitas. I just updated Entitas from 0.46.3 to 0.47.7. It's works fine when I generate in Unity. But when I follow the settings in #561 and successfully run gen code on CLI, some errors appear, like this one 
![tim 20180118180108](https://user-images.githubusercontent.com/17950537/35092599-d99a0c9c-fc7a-11e7-811b-88c4866e0b8d.png)
And I found a Components folder in Generated folder which didn't exist before.
![inkedtim 20180118170152_li](https://user-images.githubusercontent.com/17950537/35092717-3dba9bec-fc7b-11e7-8a3f-b5d62b464c50.jpg)
That Components folder contains many component, like this one
![tim 20180118180451](https://user-images.githubusercontent.com/17950537/35092779-6af5f200-fc7b-11e7-97c9-aad89e24ac95.png)
I tried to fix it by adding partial, but it appears hundreds of errors...
I also create a new project, import 0.46.3 and set up at first. Then I import 0.47.7 and follow the same setting. It works... I am pretty sure the setting is totally the same. I can't find out where the problem is. Do you guys have the same problem with me? I would appreciate it if you could tell me how to fix it. 

Here is my properties for Roslyn.
```csharp
Jenny.SearchPaths = Jenny/Plugins/DesperateDevs, \
                    Jenny/Plugins/Entitas, \
                    Jenny/Plugins/Entitas.Roslyn

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor
Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = VRTriberProject.csproj
Entitas.CodeGeneration.Plugins.Assemblies = Library/ScriptAssemblies/Assembly-CSharp.dll
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input, \
                                          Platform, \
                                          Game_HideAndSeek, \
                                          Game_Killer

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets/Sources
Jenny.Ignore.Keys = 
```

Thanks!

**Comment by sschmid** [comment]
In your image I see it generated a component for a component :) There's a feature in Entitas where you can add an attribute like [Game] to any class (not an IComponent) and it will generate a component for you. Looks like your project was in a bad state and the parser didn't get that those classes were IComponents already. Is that possible? When you upgraded to 0.47.x, did you project compile?

**Comment by sschmid** [comment]
This also explains that the compiler suggests to add the partial keyword (which you shouldn't do) because you already have a component, but another one got generated for you.

**Comment by sschmid** [comment]
Not very important but, did you run `jenny doctor` or `jenny fix`, it should offer you to remove the key `Entitas.CodeGeneration.Plugins.Assemblies`. Doesn't really matter and it's not important, just saw that you're using roslyn, so this key can be removed as it's not used anymore by any plugin. Again, `jenny fix` will tell you more about it

**Comment by CuiXiaoliang** [comment]
Thanks very much! But I can't really get it, here is my definition for component
```
using System.Collections.Generic;
using Entitas;
using Entitas.CodeGeneration.Attributes;

[Platform,Unique]
public sealed class FriendsComponent : IComponent {

    public List<UserInfoObject> friends;
}
```
is this wrong? Or is there anything you know that can lead to this problem?
And yes, I run jenny fix, it's very useful :)

**Comment by sschmid** [comment]
@CuiXiaoliang does this issue still exists in Entitas 1.4.1? If not, feel free to close this issue
