### ISSUE TITLE
Unity GUI bugs on Windows

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas#583]
Hi,

I experience more and more Unity GUI glitches, most of them Windows only. Unity for Mac seems to work as expected. And it has gotten even worse in Unity 2017.3. Some of these bug were introduced by 2017.3 and you won't see them in 2017.2.

Good news is, that those error messages can be ignored and don't affect the functionality.

For now, I will ignore the following issues you guys reported, as I think there's nothing I can do about it and I wait for Unity to fix those issues. Some of the issues originate from `UnityEngine.Experimental`, which is another reason I think I can't do anything about it. Known issues are:

---
After generating in Unity

```
Reload Assembly called from managed code directly. This will cause a crash. You should never refresh assets in synchronous mode or enter playmode synchronously from script code.
UnityEditor.EditorUtility:ClearProgressBar()
Behave.Editor.Compiler:DoCompile(IBehaveAsset, Boolean)
Behave.Editor.Compiler:Compile(IBehaveAsset, Boolean)
BehaveMenu:Compile(Boolean) (at Assets/Behave/Editor/BehaveMenu.cs:55)
BehaveMenu:Compile() (at Assets/Behave/Editor/BehaveMenu.cs:31)
BehaveAssetEditor:Update() (at Assets/Behave/Editor/BehaveAssetEditor.cs:36)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Solution: ??
This error message can be ignored. It doesn't affect the functionality

---

When clicking the Auto-Import Button and then confirming "Continue and Overwrite"

```
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:296)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7782)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7762)
UnityEditor.EditorGUILayout.LabelField (UnityEngine.GUIContent label, UnityEngine.GUIContent label2, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6187)
UnityEditor.EditorGUILayout.LabelField (System.String label, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6143)
DesperateDevs.Unity.Editor.PreferencesWindow.drawException (System.Exception exception)
DesperateDevs.Unity.Editor.PreferencesWindow.drawContent ()
DesperateDevs.Unity.Editor.PreferencesWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.OldOnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:107)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt) (at /Users/builduser/buildslave/unity/build/Runtime/UIElements/Managed/IMGUIContainer.cs:179)
```

Solution: Don't click "Continue and Overwrite" with the mouse, but use the enter key on your keyboard.
(I know, sounds weird, but works)

---

Dropdowns for Data Providers, Code Generators and Post Processors show `Mixed...` instead of `Everything`

Solution: ??
This can be ignored. Unity 2017.3 introduces this GUI bug

**Comment by IsaiahKelly** [comment]
I was planning on improving and polishing many aspects of the Entitas Unity GUI and visual debugger months ago, but I could never get the Entitas source code setup for development properly. 😞 Meaning I couldn't test any changes I made before submitting a PR. So it would have been kind of like throwing darts in the dark and hoping they landed 😧. Forget about TDD. This is UTD! (Untested development) Ha!

If I ever figure out how to get it working, I'd be more than happy to try and fix these issues on Windows and improve things overall.

**Comment by sschmid** [comment]
I can help you set it up. I recently updated [CONTRIBUTING.md](https://github.com/sschmid/Entitas-CSharp/blob/develop/CONTRIBUTING.md).

The bee script might need slight adjustment for windows. If you want we can work together on making the bee build script also work on windows out-of-the-box.

At a first glance, you probably have to either install mono on windows or replace `xbuild` with `msbuild`. Other than that it's simple bash, so we should be able to make it work on windows

**Comment by sschmid** [comment]
It's those 3 command that need to work for local building, testing and syncing new code to the Unity projects

$ ./Scripts/bee tests
$ ./Scripts/bee build
$ ./Scripts/bee sync

**Comment by sschmid** [comment]
Let's move this discussion to #586
