### ISSUE TITLE
Jenny-Install script, please help windows users

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas#636]
I will add a Jenny-Install script so no one has to manually unzip Jenny anymore.

Can someone please help to translate this to batch?

Thanks!

here's the bash version
```
path=$(find . -name Jenny.zip)
unzip "${path}" -d .
```

step 1: find Jenny.zip
step 2: unzip to current folder

**Comment by vorrin** [comment]
this assigns the path : 

`for /f "tokens=*" %a in ('dir Jenny.zip /b /s') do set p=%%a;`

to a variable p that you can echo or access(<-assumption) with:

`echo %%p` 

I think you'll then need to package some zip program with it, I got one [here](http://stahlworks.com/dev/index.php?tool=zipunzip)  not sure if the licence is  ok with what you need, but with that, this line should do what you want:

`for /f "tokens=*" %a in ('dir Jenny.zip /b /s') do  unzip -d  ../tmptest/ %a`

**Comment by RomanZhu** [comment]
here is the part for extracting ( you need to set absolute filePath)
```
Call :UnZipFile "./" filePath
exit /b

:UnZipFile <ExtractTo> <newzipfile>
set vbs="%temp%\_.vbs"
if exist %vbs% del /f /q %vbs%
>%vbs% echo Set fso = CreateObject("Scripting.FileSystemObject")
>>%vbs% echo If NOT fso.FolderExists(%1) Then
>>%vbs% echo fso.CreateFolder(%1)
>>%vbs% echo End If
>>%vbs% echo destFolder = fso.GetAbsolutePathName(%1)
>>%vbs% echo set objShell = CreateObject("Shell.Application")
>>%vbs% echo set FilesInZip = objShell.NameSpace(%2).Items()
>>%vbs% echo objShell.NameSpace(destFolder).CopyHere(FilesInZip, 16)
>>%vbs% echo Set fso = Nothing
>>%vbs% echo Set objShell = Nothing
>>%vbs% echo Set FilesInZip = Nothing
cscript //nologo %vbs%
if exist %vbs% del /f /q %vbs%
pause
```

**Comment by majorika** [comment]
how about using powershell?

write unzip.ps1 file:
```
# step 1: find Jenny.zip 
$jennyPath = gci -filter "Jenny.zip" -recurse | Select-Object -ExpandProperty FullName

# step 2: unzip to current folder
$ShellExp = New-Object -ComObject Shell.Application
$zip = $ShellExp.NameSpace($jennyPath)
$pwd = (Get-Item -Path ".\").FullName
$dest = $ShellExp.NameSpace($pwd)
$dest.Copyhere($zip.items(), 0x14) # 0x14 : do not display progress window and 'yes to all', more info: https://msdn.microsoft.com/en-us/library/windows/desktop/bb787866(v=vs.85).aspx
```

you can run this script (using batch file or command line)
`powershell -executionpolicy bypass -Command "./unzip.ps1"`

**Comment by sschmid** [comment]
Thanks everyone ❤️
