### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by nbreum15** [sschmid/Entitas#639]
Hi,

Is it possible to introduce a flag like `ignoreNamespace` to begin fields with uppercase? For example, instead of generating `contexts.game.CreateEntity();` it would generate `contexts.Game.CreateEntity();`.

Likewise, code like this:
`entity.id.Value --> entity.Id.Value`.

If you begin fields with uppercase in components, another issue is when event listeners are generated. If I follow the convention that public fields should begin with uppercase:

```
class AssetComponent
{
    public string Name;
}
```

It generates:

```
public interface IAssetListener {
    void OnAsset(CoreEntity entity, string Name);
}
```
Which, does not follow the conventions that parameter names should begin with lowercase (I see that this is because the field name is copied directly from the component).

I know that Unity uses this coding convention which is why Entitas probably does too. 
However, as someone who follows different naming conventions, i.e. [the ones you normally follow when coding in C#](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions), a flag to force fields to begin with uppercase would be greatly appreciated 😄 .

Regards, nbreum15.

**Comment by sschmid** [comment]
Hi,

I understand. This has a very low prio for me which means I will probably never do this.

You can see how I solved it with ignoring namespace and suggest doing it the same way.
see: https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/Configs/IgnoreNamespacesConfig.cs

If you fork Entitas you can see how and where this class is used. To make my life easier I added method that returns the correct value
see: https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/CodeGenerators/CodeGeneratorExtentions.cs#L13-L15

I guess in the fashion you could solve the naming convention. Feel free to create a pull request if you added it.

**Comment by DianeOfTheMoon** [comment]
I think I'm going to take a look at this.  Any suggestions for the config key before I get started?  `Entitas.CodeGeneration.Plugins.CSharpNamingConventions`?

**Comment by sschmid** [comment]
@nbreum15 
Good news, I will extract code gen templates to text files, so it will be very easy to change the output of the code generator, e.g. changing naming convention or even adding adn removing features!

See
https://github.com/sschmid/Entitas/issues/992#issuecomment-1227761712
