### ISSUE TITLE
Different Inputs

### ISSUE THREAD

**Issue by Zifkan** [sschmid/Entitas#652]
Hi,
I have some Characters in game. One Controlled by player and others through network by another players. So i have InputSystem which Getting player Inputs and send data through MovementInputComponent. So main logic of inputs Keyboard or Network take out to IInputService(in my example here its for Keyboard).
So should i create one more System for Network Inputs and release IInputService for network. Or i can use all in one system? 
Anyway MovementInputComponent equals how many characters in game. Every character has its own 
MovementInputComponent. And how can i detect what MovementInputComponent belong to 

    public class EmitInputSystem : IInitializeSystem, IExecuteSystem
    {
        Contexts _contexts;
        IInputService _inputService;
        InputEntity _inputEntity;  

        public EmitInputSystem(Contexts contexts, IInputService inputService)
        {
            _contexts = contexts;
            _inputService = inputService;
        }

        public void Initialize()
        {
           // _contexts.input.isInputManger = true;
            _inputEntity = _contexts.input.CreateEntity();
         
        }

        public void Execute()
        {
           
            _inputEntity.ReplaceMovementInput(_inputService.Horizontal, _inputService.Vertical);
        }
    }

So then another system should react on MovementInputComponent and moves what character 
MovementInputComponent was used. Need to link game context and input context to Charcacter make some equals or what way to connect Character to its own MovementInputComponent.

    public class CharacterMovementSystem :  ReactiveSystem<GameEntity>
    {
        readonly Contexts _contexts;
        private readonly MovementInputComponent _movementInputComponent;

        public CharacterMovementSystem(Contexts contexts) : base(contexts.game)
        {
            _contexts = contexts;
       
        }

        protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
        {
            return context.CreateCollector(GameMatcher.CharacterPosition);
        }

        protected override bool Filter(GameEntity entity)
        {
            return entity.hasCharacterPosition;
        }

        protected override void Execute(List<GameEntity> entities)
        {
            foreach (var e in entities)
            {
                e.ReplaceCharacterPosition(new Vector3(_movementInputComponent.horizontal, 
                 _movementInputComponent.vertical, 0));
            }
       
            Debug.Log("horizontal = " + _movementInputComponent.horizontal);
            Debug.Log("vertical = " + _movementInputComponent.vertical);
        }
    }

I realy can't understand how to do it properly. I need some help and example with it 

Cheers

**Comment by RomanZhu** [comment]
I think it should be this way:

Your characters should have some IdComponent 

Then you should have 2 input entity emitters, local and network, they both emit entities with MovementInputComponent AND IdComponent of character it belongs to

Then you should have system that loops through all MovementInputComponent with IdComponent 
and if it finds Character with same IdComponent, then it applies MovementInputComponent values to position.

**Comment by Zifkan** [comment]
AS i understood "2 input entity emitters" you mean create two separated Systems?

**Comment by Zifkan** [comment]
I tryed as u say, but just with hardcode for main character 

    readonly Contexts _contexts;
    private IGroup<GameEntity> _characters;


    public CharacterMovementSystem(Contexts contexts) : base(contexts.input)
    {
        _contexts = contexts;
        _characters = contexts.game.GetGroup(GameMatcher.AllOf(GameMatcher.PlayerId, GameMatcher.CharacterPosition));
    }


    protected override ICollector<InputEntity> GetTrigger(IContext<InputEntity> context)
    {
        return context.CreateCollector(InputMatcher.MovementInput);
    }

    protected override bool Filter(InputEntity entity)
    {
        return entity.hasMovementInput;
    }

    protected override void Execute(List<InputEntity> entities)
    {
        foreach (var e in entities)
        {
            if (e.movementInput.playerId == 1)
            {
               var player =  _characters.GetEntities().FirstOrDefault(entity => entity.playerId.value == e.movementInput.playerId);
                player.ReplaceCharacterPosition(new Vector3(player.characterPosition.value.x+ e.movementInput.horizontal, player.characterPosition.value.y + e.movementInput.vertical, 0));
                
            }
        }
    }

i think its looks like some ugly or im mistaken

**Comment by Cosmik11** [comment]
hmm, If you want the system above to be a strictly be a charachter movement system for the local charachter that is controlled through the key board then I would add 
`entity.movementinput.playerID==1`

However on first thought if you wanted not a charactermovement system but just a movement system for both local and network charachters Prehaps something like this:
```
[Game]
public struct PlayerIDComponent: IComponent
{

[EntityIndex]
public int value

}
```
with the EntityIndex attribute on your field you can search directly through the context. lets say ID of 1 is a local charterer and ID of 2 is a network character so then maybe you could have something like this 

```
readonly Contexts _contexts;
GameContext _Gamecontext;

public MovementSystem(Contexts contexts) : base(contexts.input)
{
    _contexts = contexts;
_Gamecontext=contexts.game;
}


protected override ICollector<InputEntity> GetTrigger(IContext<InputEntity> context)
{
    return context.CreateCollector(InputMatcher.MovementInput);
}

protected override bool Filter(InputEntity entity)
{
    return entity.hasMovementInput;
}

protected override void Execute(List<InputEntity> entities)
{
    foreach (var e in entities)
    {
        if (e.movementInput.playerId == 1)
        {
            foreach (var charachter in _Gamecontext.GetEntitiesWithID(1))
            {
                //movement code for local charachters here here
            }
        }

        else
        {
            foreach (var networkcharachter in __Gamecontext.GetEntitiesWithID(2))
            {
                //movement code for network charachters herehere 
            }
        }
    }
}

```
` __Gamecontext.GetEntitiesWith*insertcomponentname*()` returns a hashset which is quick to iterate through

**Comment by Cosmik11** [comment]
on a second look it might look cleaner to separate network movement into another system because the one I just wrote looks a little wild haha but thats the idea

**Comment by Zifkan** [comment]
Ty for advice but a bit late im already realize with one system for local and network, but im thinking about separate it.
I created Input Identifer:
```
[Input]
public class InputPlayerIdentifierComponent: IComponent
{
    public int playerId;
}
```
and have Movement Component:
```
 [Input]
 public class MovementInputComponent: IComponent
  {
        public float horizontal;
        public float vertical;
   }
```
Emit Input System which always emit Identifier and then another inputs:
```
public class EmitInputSystem : IInitializeSystem, IExecuteSystem
    {
        Contexts _contexts;
        IInputService _inputService;
        InputEntity _inputEntity;

        public EmitInputSystem(Contexts contexts)
        {
            _contexts = contexts;
            _inputService = _contexts.meta.inputService.instance;
        }

        public void Initialize()
        {
           _inputEntity = _contexts.input.CreateEntity();
        }

        public void Execute()
        {
           _inputEntity.ReplaceInputPlayerIdentifier(Random.Range(0, 9)); // Just for test while haven't network implementation
           _inputEntity.ReplaceMovementInput(_inputService.Horizontal, _inputService.Vertical);
           _inputEntity.ReplaceRotationInput(_inputService.RotationX, _inputService.RotationY);      
        }
    }
```


And Movement System:
```
public class CharacterMovementSystem : ReactiveSystem<InputEntity> //IExecuteSystem//
{
    readonly Contexts _contexts;


    public CharacterMovementSystem(Contexts contexts) : base(contexts.input)
    {
        _contexts = contexts;
    }


    protected override ICollector<InputEntity> GetTrigger(IContext<InputEntity> context)
    {
        return context.CreateCollector(InputMatcher.AllOf(InputMatcher.InputPlayerIdentifier,InputMatcher.MovementInput, InputMatcher.RotationInput));
    }

    protected override bool Filter(InputEntity entity)
    {
        return entity.hasInputPlayerIdentifier && entity.hasMovementInput && entity.hasRotationInput;
    }

    protected override void Execute(List<InputEntity> entities)
    {

        foreach (var e in entities)
        {
            var player = _contexts.game.GetEntitiesWithPlayerId(e.inputPlayerIdentifier.playerId).SingleEntity();
            player.ReplacePosition(new Vector3(player.position.value.x + e.movementInput.horizontal, 0, player.position.value.z + e.movementInput.vertical));
            player.ReplaceRotation(Quaternion.Euler(2 * e.rotationInput.AxisY, 2 * e.rotationInput.AxisX, 0));            
        }
    }
}
```
Im confused is using GetEntitiesWithPlayerId generated method properly way and may be its really better use two systems

**Comment by ropollock** [comment]
Seems to me if you have two separate behaviors for local or networked you should have two separate systems to maintain a single responsibility for a system. You just need to find a good filter to differentiate between the two player types for each system.

**Comment by Cosmik11** [comment]
when you use  the entity index attribute as I did the GetEntitiesWithPlayerId  is a generated method that returns a hash-set of all the entities inside the context that has the given ID

**Comment by Zifkan** [comment]
Im still confused its bad practice to use GetEntitiesWithPlayerId or not?

**Comment by sschmid** [comment]
The way I once solved this is that each player has a unique id. When you create the input entity (btw, I create new Input entities everytime and not reuse a single one, because you might have multiple inputs for each player) this entity will also contain the id of the player it belongs to. I have a single ProcessInputSystem where I apply the input on the corresponding player with GetEntityWithPlayerId. 

> Im still confused its bad practice to use GetEntitiesWithPlayerId or not?
Good practice! But would recommend a PrimaryIndex instead of a normal one for this case

**Comment by sschmid** [comment]
The local InputController creates inputs for the local player. The NetworkController creates inputs based on the information coming from the network command which should contain the playerID

**Comment by Zifkan** [comment]
@sschmid, as i understood for example i have 10 characters with IDs form 1 to 10. And im creating 10 MovementInputComponents for of each character. Should this components all been created once and reused each other or what u mean "create new Input entities everytime and not reuse a single one" ?

**Comment by sschmid** [comment]
See [Match One - /InputController.cs](https://github.com/sschmid/Match-One/blob/master/Assets/Scripts/Controllers/InputController.cs#L24-L25)

and 
[InputSystem.cs](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Systems/Game/Systems/InputSystem.cs#L33-L37)

I suggest to create and destroy inputs all the time. Don't worry, Entitas is object pooling and reusing all entities and components, so creating and destroying entities is not a problem
