### ISSUE TITLE
Entitas 1.4.2: Visual Debugging does not work properly at Unity 2017.3.1 

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas#653]
@sschmid  It throws me this error when I select the system game object to see the system debugging message and the time of Execute systems all become red. 
```
KeyNotFoundException: The given key was not present in the dictionary.
System.ThrowHelper.ThrowKeyNotFoundException () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
DesperateDevs.Serialization.Properties.get_Item (System.String key) (at <099e51ab2dc047729b0674a5e3327d54>:0)
DesperateDevs.Serialization.Preferences.get_Item (System.String key) (at <099e51ab2dc047729b0674a5e3327d54>:0)
Entitas.VisualDebugging.Unity.Editor.VisualDebuggingConfig.get_systemWarningThreshold () (at <208de3a2d6014ccb96680dd370edf0de>:0)
Entitas.VisualDebugging.Unity.Editor.DebugSystemsInspector.OnEnable () (at <208de3a2d6014ccb96680dd370edf0de>:0)
```
![image](https://user-images.githubusercontent.com/7009368/37330073-de0f0450-26da-11e8-96c5-342b6b1dc67b.png)

**Comment by roygear** [comment]
I am using Windows 7 + Unity 2017.3.1p2 + Entitas 1.4.2. It is working fine.

**Comment by sschmid** [comment]
Please open the Entitas preferences in Unity once and close it and see if this fixes the issue

**Comment by optimisez** [comment]
> Please open the Entitas preferences in Unity once and close it and see if this fixes the issue

@sschmid Still the same error but I have a interesting finding. When u keep Entitas preference window open, the error does not appear anymore and visual debugging works properly. lol

![image](https://user-images.githubusercontent.com/7009368/37336843-8eb670ec-26ed-11e8-9657-9848590d84fc.png)

**Comment by sschmid** [comment]
When you open the Preferences, Entitas will automatically add missing keys. Make sure your properties contain these keys

```
Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold = 5
Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath = Assets/Editor/DefaultInstanceCreator
Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath = Assets/Editor/TypeDrawer
```

**Comment by sschmid** [comment]
Your error says it couldn't find `SystemWarningThreshold`

**Comment by optimisez** [comment]
> When you open the Preferences, Entitas will automatically add missing keys. Make sure your properties contain these keys

@sschmid Yes. I have those keys included. I uploaded my UnityPreferences.properties for you to check it out.
[UnityPreferences.properties.txt](https://github.com/sschmid/Entitas-CSharp/files/1806799/UnityPreferences.properties.txt)

**Comment by sschmid** [comment]
Why is it called UnityPreferences, do you have multiple? If so, what does the button in the Entitas logo say?

**Comment by optimisez** [comment]
> Why is it called UnityPreferences, do you have multiple? If so, what does the button in the Entitas logo say?

@sschmid Yup. I have UnityPreferences.properties for Unity and Entitas.properties for Roslyn. I think I selected UnityPreferences.properties properly. 

![image](https://user-images.githubusercontent.com/7009368/37341402-37daff68-26fc-11e8-9e75-c366fe17f128.png)

**Comment by sschmid** [comment]
Ok, then I need to try to reproduce.

Maybe as a workaround (just guessing) add those keys also to the roslyn properties, maybe that helps

**Comment by optimisez** [comment]
> Maybe as a workaround (just guessing) add those keys also to the roslyn properties, maybe that helps

@sschmid Ya. Problem fixed. after adding those keys to roslyn properties I guess it still read roslyn properties file instead of UnityPreferences properties file.
