### ISSUE TITLE
[Question] Reactive systems without Execute() ?

### ISSUE THREAD

**Issue by DuckOfDoom** [sschmid/Entitas#657]
Hello, I have a question.

How do I make reactive systems that don't rely on the loop to react to something? What if I need to do something exactly when component updates, not the next frame/fixed update?

Thanks in advance.

**Comment by sschmid** [comment]
Hi, you can use group.OnEntityAdded +=

This will execute code immediately when sth changes.

But: I strongly recommend not using it and consider reactive systems instead.
Only use direct events when you're fine with the consequences. Consequences are less control over the order and that code in other places will be executed directly

**Comment by DuckOfDoom** [comment]
@sschmid Thanks a lot.

**Comment by DuckOfDoom** [comment]
@sschmid  I think it might be useful if I, for example, want to abstract my logging system. I'd have log component and will create entitites with this component when I need to log something. Is it a good way of doing so?
