### ISSUE TITLE
Code generation without Unity

### ISSUE THREAD

**Issue by FastQuagga** [sschmid/Entitas#659]
Hi,

Where can I find a manual to setup Entities (with code generation) for the C# project (without Unity)?  Seems an old manual isn't actual.

**Comment by Aslan85** [comment]
Hi,
Simon did a youtube video to set the code generation in a terminal.
It was 6 days ago, you have probably your answer but I send the link -> https://youtu.be/L-18XRTarOM

**Comment by ResourceHog** [comment]
This link uses unity

**Comment by sschmid** [comment]
@FastQuagga Here's a sample Entitas project as a dotnet console app including a working Jenny setup

[Entitas-Standalone](https://github.com/sschmid/Entitas-Standalone)
