### ISSUE TITLE
Question: UML for Entitas

### ISSUE THREAD

**Issue by r3b00t5** [sschmid/Entitas#660]
Hi,

I have question.

I'm having a bit of a hard time thinking of my old project from an ECS perspective. One way I thought that may help would be to map it out with a UML Composite Diagram. Has anyone done this before?

**Comment by sschmid** [comment]
Not UML, but that's why we have somewhere in the wiki

```
+------------+       +------------+       +------------+       +------------+
|            |       |            |       |            |       |            |
|   System   | +---> |   System   | +---> |   System   | +---> |   System   |
|            |       |            |       |            |       |            |
+------------+       +------------+       +------------+       +------------+
```


```
                      +------------------+
                      |       Pool       |
                      |------------------|
                      |    e       e     |      +-----------+
                      |        e     e---|----> |  Entity   |
                      |  e        e      |      |-----------|
                      |     e  e       e |      | Component |
                      | e            e   |      |           |      +-----------+
                      |    e     e       |      | Component-|----> | Component |
                      |  e    e     e    |      |           |      |-----------|
                      |    e      e    e |      | Component |      |   Data    |
                      +------------------+      +-----------+      +-----------+
                        |
                        |
                        |     +-------------+
                        |     |      e      | Groups
                        |     |   e     e   |
                        +---> |        +------------+
                              |     e  |    |       |
                              |  e     | e  |  e    |
                              +--------|----+    e  |
                                       |     e      |
                                       |  e     e   |
                                       +------------+
```

**Comment by ethankennerly** [comment]
@r3b00t5 That's a great example of a UML diagram for an ECS-architected game!

Everyone,

How would you automatically generate a system diagram from a game that is using Entitas?

I'm looking for ideas.

One idea is to augment the nice visual debugger, so you can see the diagram as you play.

I haven't found an entity-retained event, so I would make a middleman reactive system class that the game reactive systems extend from.  When compiled for debug visualization, in the execute method, I would place the debug entity game object in front of the debug system game object.

I would make a sprite and text mesh for each entity.  The text would be the string value of the entity.

To see how an entity goes from one system to another, I would going to visualize a trail from one system to the next.  

I would layout a collection of systems (called a feature) as a row of sprites, one sprite for each terminal system.

I would layout a series of systems in their execute order.

What ideas do you have to quickly and automatically visualize the relationships between systems?

**Comment by StormRene** [comment]
I would not make the visualizer part of my game solution, therefore pack it into a own solution - like tests. I Would probably write some WPF program because the WPF UI is easy to handle. To show the realtionships between systems I would do:
1. Show the execute order
2. Show Input (Collector and Filter)
3. Show Output (ReplaceX and AddX, CreateEntity, DestroyEntity etc. pp.)
Maybe 2/3 can be neat visualized as data transformation in some way?
To accomplish this I would say attributes over the system which specifies the types of input and output is an easy way. Otherwise reflection could be an option but seems hard to achieve. How to get the filter for example?

**Comment by ethankennerly** [comment]
For what it's worth, in a weekend, I diagrammed and logged flow through any observable Entitas system.

https://github.com/ethankennerly/Entitas-VisualDebugging-System-Flow
