### ISSUE TITLE
DesperateDevs.CodeGeneration.Plugins.TargetDirectory should be relative to the project.

### ISSUE THREAD

**Issue by bfsrjose** [sschmid/Entitas#683]
Hi,

I have a suggestion:

DesperateDevs.CodeGeneration.Plugins.TargetDirectory

is relative to the properties file, but is inserted into the project file, if the project file and the properties file are not in the same directory this results in broken paths in the project file. I would suggest making the paths inserted into the project file relative to the project file. (even should the target directory remain relative to the properties file).

Cheers

**Comment by sschmid** [comment]
Hi, that's correct.
All paths specified in the properties file are always relative to the location of the properties file.
Is there a reason why you can't have the properties in the same folder?

**Comment by sschmid** [comment]
Ok, just followed up on the chat and saw your messages. Did you make progress, or do you still have issues?
If so, could you briefly outline your setup, so we can try to find a solution

**Comment by bfsrjose** [comment]
I found a workaround, I have a csproj next to the properties file that I'm using just for Jenny (jenny.csproj).

The overall project setup is kind of like this:

Assets
Assets/Built/library1.dll
Assets/Built/library2.dll
ExternalProjects/Library1/library1.csproj 
ExternalProjects/Library2/library2.csproj
Jenny.csproj
entitas.properties
entitasAssembly.properties

So right now I have library1.csproj and Jenny.csproj pointing at the same files and a separate entitas properties file for building without Jenny from the assemblies that are added to the Assets folder.
