### ISSUE TITLE
Don't auto modify .properties files

### ISSUE THREAD

**Issue by bfsrjose** [sschmid/Entitas#686]
Hi,

I have a suggestion:

We have several unrelated .properties files (e.g. gradle.properties) that the Entitas gui in editor modifies. It would be good to have a known prepend or a request to save before any modifications are made to those files.

Cheers

**Comment by c0ffeeartc** [comment]
yep, `.properties` extension is too general, could be changed to `.entitassettings` or `.entitasprefs`

**Comment by sschmid** [comment]
Entitas only modifies `Entitas.properties`.
Feel free to reopen and provide more details on how to reproduce.
