### ISSUE TITLE
i want see DesperateDevs.Util source code. 

### ISSUE THREAD

**Issue by woshihuo12** [sschmid/Entitas#692]
i notice there are some DesperateDevs libs, i want to see their source code.
so where can i find them?

**Comment by sschmid** [comment]
Hi,

DesperateDevs is not open source.
If you want source access we can negotiate sth.

**Comment by sschmid** [comment]
@woshihuo12 

Desperate Devs is open-source now!
See: [One Entitas version - Desperate Devs is open-source now](https://github.com/sschmid/Entitas/discussions/1008)

Please also see [CHANGELOG.md](https://github.com/sschmid/DesperateDevs/blob/main/CHANGELOG.md#100---2022-09-01)

DesperateDevs.Util is split into
- DesperateDevs.Caching
- DesperateDevs.Extensions
- DesperateDevs.Reflection

Have fun! :D
