### ISSUE TITLE
`InputComponentsLookup' does not exist in the current context

### ISSUE THREAD

**Issue by burley1** [sschmid/Entitas#696]
Hi,

I updated Entitas from 0.47.2 to 1.5.2
Then i run generation. For some reason GameComponentsLookup and InputComponentsLookup was removed! And i have error:
Assets/Sources/Generated/Input/InputContext.cs(18,17): error CS0103: The name `InputComponentsLookup' does not exist in the current context

Cheers

**Comment by sschmid** [comment]
Sound like there was an issue with the code generator, probably changes in the properties file.
Is this still an issue?

**Comment by burley1** [comment]
Hi, I started all from the begging - I removed all generated code, removed system, then add components again and error disappear. Anyway i can't reproduce this error so issue can be closed.
