### ISSUE TITLE
Q: Entitas in Following Usecase

### ISSUE THREAD

**Issue by kenofori** [sschmid/Entitas#702]
Hi,

Entitas on sale which is gonna over in few days and i want to clear all of my confusions. For example, according to my limited knowledge Entitas is only useful when there is a lot of instantiating/destroying? I couldnt find any detailed link on Job system so cant tell if it'd solve some issues.

To further clear my question. i have a seperate scene in my game, where
a- 2 fixed buttons in ui (Load, Save) which load a texture from album or camera or save a to album.
b- a RawImage for texture preview
c- dropdown with 3 options that apply a shader on that texture.

Does using entitas in this v small case make sense? even if not, then why using entitas in this case'd make it better for future?

im asking such basic question from a noob perspective, so please bear with me

Cheers

**Comment by c0ffeeartc** [comment]
This setup is too simple. Without Entitas that would be only few functions and MonoBehaviours.
Entitas helps building architecture good for extension, if you plan add a lot more features it can become useful.
 Simple project could be good to learn, try out Entitas routines, check if it fits you

**Comment by sschmid** [comment]
I follow this diagram #610 
Your use case mentions what I would put in the View layer. Entitas is powerful and very useful for the game logic part. I would probably implement what you described in Unity
