### ISSUE TITLE
Entitas for a Static Scene

### ISSUE THREAD

**Issue by aammfe** [sschmid/Entitas#710]
Hi

I went through the documentation (which is quite weak honestly for a new comer) and still have a lot of questions and confusions. Even your example project are just one scene based not even fully following the guide you wrote.

So instead of asking for an ideal documentation, i decided to write a simple game but with 2-3 differenet scenes with their own relevant stuff that i'll build and hopefully with your timely support, can learn and use it

So first scene is a menu screen, user will be rarely coming back to menu screen so i find it better organizeable in a seperate screen. Especially when menu screen will have some 3d part of the game running in background (just a fraction of actual game level)

So please point me to either a link or your repo where we handle such static ui in entitas ways. 

Thanks

PS: i bought the Entitas anyway to show my support in last sale.

**Comment by c0ffeeartc** [comment]
Here is one way - create Main scene, put GameController into it, load it at startup and never unload it. Load/unload all other scenes additively.
How and when you load/unload is up to you

**Comment by aammfe** [comment]
Thank you for your reply,

Question, why not unload this main menu scene along with related controller? Wouldn't it be an issue if lets say main menu scene is quite graphic heavy and even disabling it might take some memory?

**Comment by aammfe** [comment]
That makes sense now, Thanks :)
Unloading other scenes means their systems can be destroyed too, which is great.

Continuing, as Match 3 only has just one score field, is there any heavy ui related example project (with more buttons, HUd etc) so i can learn from it how to handle these fixed already drawn elements in entitas?

**Comment by c0ffeeartc** [comment]
For ui refreshing there is [Events feature](https://github.com/sschmid/Entitas-CSharp/wiki/FAQ#events-feature-does-not-trigger). Chatting in [gitter](https://gitter.im/sschmid/Entitas-CSharp) may get you additional answers
