### ISSUE TITLE
How to use Lua scripts in Entitas?

### ISSUE THREAD

**Issue by Wolf-Warriors** [sschmid/Entitas#718]
Hi,

I have an question

I am doing a big project and need hot update code.
How to use Lua scripts in Entitas?

Cheers

**Comment by zhuchun** [comment]
Try to use Entitas in hybrid mode, so you can have ComponentSystem + ECS + Lua and do crazy stuff. Beneath links may help.
[MultiReactiveSystem](https://github.com/sschmid/Entitas-CSharp/wiki/MultiReactiveSystem-Tutorial)
[Game Architecture With Entitas](https://github.com/sschmid/Entitas-CSharp/wiki/How-I-build-games-with-Entitas-%28FNGGames%29)

Personally, I would avoid merging an ECS framework with an existing project, it's time-consuming. Mixing up Lua, ComponentSystem, ECS is another thing I may never do, that's way hard for the whole team to follow up ;)

**Comment by StormRene** [comment]
Copy from chat:
Entitas works with code generation that needs to be recompiled. Would be very tricky to add new components to entitas and hot reload your c# part
if it's just hot loading lua scripts and the entitas side doesn't gets affected there's no problem
just use nlua or moonsharp
I mean there are options to do assembly hot reloading in c# but that's a more common problem and not related directly to entitas itself

**Comment by zhuchun** [comment]
@StormRene Agree. If I have to do this, I will try to abstract Lua parts as a service interface, Lua can hotfix the implementation while Entitas don't have to know about Lua.

**Comment by Wolf-Warriors** [comment]
您的邮件已收到！谢谢！
