### ISSUE TITLE
Code not compile after deleting a class

### ISSUE THREAD

**Issue by aammfe** [sschmid/Entitas#730]
Hello!!
I m using Jenny server .
On code generation after deleting a component class or any class which has context attribute should also delete its generated code..?

if yes then its not happening in my case.

if not then I have to  delete it manually ?

**Comment by sschmid** [comment]
Hi, yes, deleting a component should result in deleting the generated code, too.
If you don't use the roslyn code generator (comes with the asset store version) and you use the default generator in Unity, the code is not deleted automatically, because the default code generator only works when there are no compiler errors.

**Comment by kkohno** [comment]
and how to refactor? For example rename the component...

**Comment by kkohno** [comment]
I have the component Named NeedSpawn, then I rename this to TrySpawn and have a many problems with fields as below:
entity.isNeedSpawn; is not compiled
i need rename all entries to entity.isTrySpawn;

**Comment by fahall** [comment]
@kkohno I ran into this problem too. I fixed it by finding the occurrences of my component, `NeedSpawn` in your case inside the `Generated` folder. There were a few files (e.g. `GameNeedSpawn.cs` if using Game context); these can just be deleted (or renamed if refactoring) and 3 references in the generated `GameComponentsLookup.cs` file. The lines referencing the component inside `GameComponentsLookup.cs` can be renamed or deleted. Do note that if you're deleting a component, you will need to decrement the indices for all subsequent indices (e.g. `public int NeedSpawn = 8`) such that they are monotonically increasing. 


You can probably also just delete all the contents of the `Generated` directory. The only gotcha I've found there is that you need to make sure you have enumerated all of your contexts inside the Entitas menu. 

Sounds like updating to the $90 asset store version might also fix things. I'm still testing out Entitas before buying, but it's nice to know that the code generation will get out of the way more with the Roslyn version.

**Comment by kkohno** [comment]
@fahall a lot of steps for a simple renaming. By the way, simply deleting the Generate folder will have compilation errors with attributes in your code
