### ISSUE TITLE
Could not delete file 'Library/ScriptAssemblies/Assembly-CSharp.dll.bak'

### ISSUE THREAD

**Issue by aammfe** [sschmid/Entitas#731]
Hello!!
If jenny server is running in and I edit any thing in my code. 
Unity will prompt.

Could not delete file 'Library/ScriptAssemblies/Assembly-CSharp.dll.bak'
Copying assembly from directory Temp to Library/ScriptAssemblies failed

you can not delete 'Library/ScriptAssemblies/Assembly-CSharp.dll.bak' unless you close jenny server.
seems jenny server lock this file.

and I think second error is caused by first one.

each time I have to restart unity.

**Comment by sschmid** [comment]
Hi,

I'm not aware of jenny locking any files, especially .bak files. Windows is known for locking files.
DI you use custom generators? If not, check your properties file and try removing`Library/ScriptAssemblies` from the search paths or `Assembly-CSharp.dll` from your plugins if it's set

**Comment by syedhasan1964** [comment]
The only solution seems to be right-clicking on the script folder and then left clicking on the Reimport menu item.

**Comment by Angelica-0804** [comment]
reimport works! Thanks!
