### ISSUE TITLE
Roslyn integrated generation.

### ISSUE THREAD

**Issue by BenjaBobs** [sschmid/Entitas#734]
Hi, I have been lurking this repo for a while now, and I found something interesting in the [CSharpLang](https://github.com/dotnet/csharplang) repo and the [Roslyn](https://github.com/dotnet/roslyn) repo and I haven't seen mentioned here.

[Champion "Replace/original and code generation extensions"](https://github.com/dotnet/csharplang/issues/107)
[Reboot build chain codegen](https://github.com/dotnet/roslyn/issues/19505)

![](https://user-images.githubusercontent.com/715038/41872031-0798e0f6-78c1-11e8-8485-ec21a62aad7b.png)

It is probably not at a stage where it is quite useful for Entitas, however I think it might be in the future.

**Comment by sschmid** [comment]
Thanks for the links!
