### ISSUE TITLE
Code Generator generates invalid code for components whose names are C# keywords

### ISSUE THREAD

**Issue by akanix42** [sschmid/Entitas#744]
Only recently started using Entitas, gotta say it's really awesome!
I just ran into this issue while setting up some components:

Create a `BaseComponent`:
```csharp
using Entitas;

[Game]
public sealed class BaseComponent : IComponent
{
  public string value;
}

```
Run the `Generate` command in Unity.

The generated code has errors because `base` is a keyword in C#. My key takeaway is to just note that you can't use keywords as your component names (which of course makes sense, since you can't use keywords as variable names). However, it would be nice if the generator displayed a friendly error instead of generating invalid code.
 
The error message is: 
```
Assets/Sources/Generated/Game/Components/GameBaseComponent.cs(11,29): error CS1519: 
Unexpected symbol `base' in class, struct, or interface member declaration
```
Here's the generated code, for reference:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public BaseComponent base { get { return (BaseComponent)GetComponent(GameComponentsLookup.Base); } }
    public bool hasBase { get { return HasComponent(GameComponentsLookup.Base); } }

    public void AddBase(string newValue) {
        var index = GameComponentsLookup.Base;
        var component = CreateComponent<BaseComponent>(index);
        component.value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceBase(string newValue) {
        var index = GameComponentsLookup.Base;
        var component = CreateComponent<BaseComponent>(index);
        component.value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveBase() {
        RemoveComponent(GameComponentsLookup.Base);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherBase;

    public static Entitas.IMatcher<GameEntity> Base {
        get {
            if (_matcherBase == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Base);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherBase = matcher;
            }

            return _matcherBase;
        }
    }
}

```

**Comment by rglobig** [comment]
Would be possible if the generator generates it like this:
```
public BaseComponent @base { get { return (BaseComponent)GetComponent(GameComponentsLookup.Base); } }
```
The @ symbol allows you to use reserved words.

**Comment by roygear** [comment]
I implemented such "@" fashion to generator, but I don't like it. 

The interface like this:
entity.@base.value = "odd";

or add "_"
entity._base.value = "odd2";

**Comment by sschmid** [comment]
My suggestion is not to use reserved keywords

**Comment by StormRene** [comment]
I'm a bit curious here. if you use a field with @ like `int @int` you can use it like `object.int` and not `object.@int`.

**Comment by StormRene** [comment]
The API would stay the same but we could use component names like `FloatComponent`, `BaseComponent` and `EventComponent`. I can think of the following solution: the code generator has an array of all reserved keywords (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/) and if the naming matches one of these it writes it with a @.

**Comment by roygear** [comment]
I never used @ for field name, not sure any potential problem with it.

So, here is implementation which adding "_" in front of keyword.

Usage:

```Csharp
public sealed class BaseComponent : IComponent
{
    public string value;
}

	...
	
	var e = contexts.game.CreateEntity();

	e.AddBase("Add");
	e.ReplaceBase("For ReactiveSystem");
	e.RemoveBase();

	e._base.value = "For critical code";
```

This DLL based on Entitas 1.7, tested in Roslyn version

[Entitas.CodeGeneration.Plugins.dll.zip](https://github.com/sschmid/Entitas-CSharp/files/2234282/Entitas.CodeGeneration.Plugins.dll.zip)

**Comment by roygear** [comment]
which version? "_" or "@" ?

**Comment by PythagoRascal** [comment]
Personally, I'd say "@" because "_" is often used for private variables and at first glance that might be confusing.

**Comment by roygear** [comment]
PR submitted using "@" version

**Comment by sschmid** [comment]
ref #756
