### ISSUE TITLE
Updating multiplayer gamestate

### ISSUE THREAD

**Issue by spudbox** [sschmid/Entitas#750]
Hello,

Working on our game's networking piece now and looking at the best way to update game state during multiplayer games. Are there any examples out there of how to do this with Entitas?

Thanks!

**Comment by StormRene** [comment]
I assume you are talking about getting data from the backend/your server? I posted this a while ago in the gitter chat: 
I have a service that receives data from backend and can create command components with the respond packages. Every backend package consists of a set of responds 1..* with type and content. I can register for types with the method RegisterResponse<StartMissionResponse, StartMissionResponseCommandComponent>()
The implementation for that looks like this:
```
private void RegisterResponse<TResponse, TResponseComponent>()
    where TResponse : IServerResponse
    where TResponseComponent : IResponseComponent<TResponse>, new() {
    this.client.RegisterResponse<TResponse>((response) => {
        var entity = this.commandContext.CreateEntity();
        var component = new TResponseComponent {
            Value = response
        };
        entity.AddComponent(CommandComponentsLookup.componentTypeIndices[typeof(TResponseComponent)], component);
    });
}

public interface IResponseComponent<IServerResponse> : Entitas.IComponent {
    IServerResponse Value { set; }
}
```
From that point I can react as usual with reactive systems.

Register reponse in the service (client) looks like this: `void RegisterResponse<T>(Action<T> callback) where T : IServerResponse`. In the service I'm saving every registered response like that `this.clientResponses.Add(typeof(T).Name, new ClientResponse<T>(callback))`. When the backend gives me some packages I check my response dictionary and call the corresponding callbacks with the deserialized data.

**Comment by zhuchun** [comment]
1. You didn't metion about what framework/architecture you're using, that's crucial.

2. In general case, you may need a code generator/templates to help you develop your game easy and safe.

3. Wrap generated code as a service
