### ISSUE TITLE
Jenny code generation support for dot net core 2.0 project.

### ISSUE THREAD

**Issue by saviorextr** [sschmid/Entitas#759]
Hi,

I tried jenny/roselyn code generation on a dot net core 2.0 project but it wouldn't work.
So my question is, would it be possible to add this support or point to me in a direction to try and add this on my own. 

Thanks.

**Comment by sschmid** [comment]
I haven't checked, but I guess roslyn should be able to parse net core 2.0. If so, it will be possible to support

**Comment by sschmid** [comment]
If the current roslyn plugin doesn't work, we only need to update ComponentDataProvider and EntityIndexDataProvider and we should be fine

**Comment by sschmid** [comment]
Can you share more details on what didn't work?

**Comment by sschmid** [comment]
Here's a sample Entitas project as a dotnet console app using .NET 6.0 and .NET Standard 2.1, including a working Jenny setup:

[Entitas-Standalone]https://github.com/sschmid/Entitas-Standalone)
