### ISSUE TITLE
AllFeaturesGenerator

### ISSUE THREAD

**Issue by roygear** [sschmid/Entitas#762]
## Purpose
This generator will generate Feature classes which contain Feature and System class that match the order we see on the IDE.

## Install

This generator made for Roslyn version only. 

Copy the DLLs in below zip to the location where searchable for Jenny.
But do not put it into Unity's Assets folder.
[Gear.Roslyn.CodeGeneration.Plugins20180823.zip](https://github.com/sschmid/Entitas-CSharp/files/2313100/Gear.Roslyn.CodeGeneration.Plugins20180823.zip)

Run ```Jenny.exe auto-import -s ``` as usual.

Below contents will be added to the ```Preferences``` file.
```
Gear.Roslyn.CodeGeneration.Plugins
Gear.Roslyn.CodeGeneration.Plugins.DeleteEmptyFolderInAllFeaturesPreprocessor
Gear.Roslyn.CodeGeneration.Plugins.AllFeaturesDataProvider
Gear.Roslyn.CodeGeneration.Plugins.AllFeaturesGenerator
```

## Usage

Create a folder named ```AllFeatures``` inside ```Assets``` folder.

Put System class into ```AllFeatures```

### Order

Use folder for controlling exectution order of Systems.

For example, we have `A_System` and `B_System` in ```AllFeatures```:
![1](https://user-images.githubusercontent.com/30362268/44031255-f78eaa4c-9f35-11e8-814a-4c7598a1c987.jpg)

By default, ```A_System``` will be executed first. How about executing `B_System` first?

Create a folder named ```_1_OrderFeature```, and put ```B_System``` in it.

Now we have :
![2](https://user-images.githubusercontent.com/30362268/44031356-501517fa-9f36-11e8-9323-1eefa257d9aa.jpg)

Run Jenny's generation, we get:
```csharp
public sealed class AllFeatures : Feature
{
    public AllFeatures(Contexts contexts){
        Add(new _1_OrderFeature(contexts)); 
        Add(new A_System(contexts));             
    }
}

public sealed class _1_OrderFeature : Feature
{
    public _1_OrderFeature(Contexts contexts){
        Add(new B_System(contexts));             
    }
}

```

Use ```AllFeatures``` or/and other features in your GameController:

``` csharp
systems = new AllFeatures(contexts);
//or / and
systemsB = new _1_OrderFeature(contexts);
```

## Work with other generator
Some Feature class may be generated by other generator, like `EventSystem`.
To deal with it, manually create a Feature class(named `LateUpdateFeature`) and then include `EventSystem`. Create a folder named `_9_LateUpdateFeature`, put this into `AllFeatures`.

Put any System classes need to update lately into `LateUpdateFeature`, like DestroySystems.
Folder `_9_LateUpdateFeature` should be the last in `AllFeatures`.

## 
Feedback welcomed!

**Comment by sschmid** [comment]
Thanks for sharing!

**Comment by StormRene** [comment]
The only problem I see is that you have to choose naming for your systems in a feature that corresponds with the order - if you don't want to add sub-features (and they also need the correct naming for ordering). So if the `DestroyEntitySystem` should run after the `KillEntitySystem`, what do I do? Putting it in a `DestroyFeature` would end in the same result. I like the idea very much, but naming stuff with `_1_ ... _2_` doesn't seem right.

**Comment by roygear** [comment]
Use _1_..._2_... for the folder only, not for the systems

**Comment by roygear** [comment]
create a folder named `_1_KillFeature`, and put KillEntitySystem in it, that KillEntitySystem  will run first than DestroyEntitySystem.

I think we do have worry so much creating Feature classes because it is generated.

**Comment by roygear** [comment]
about idea of the naming _1_..._2_..., it is come from Unit Test

**Comment by roygear** [comment]
Update:
added `DeleteEmptyFolderInAllFeaturesPreprocessor` and error message if there is same folder name in `AllFeatures `
