### ISSUE TITLE
Jenny - parsing the project file takes several minutes

### ISSUE THREAD

**Issue by kdrzymala** [sschmid/Entitas#767]
Hi! 
Looks like I'm facing similar issue like #758 but solution provided there does not work. I don't have multiple csproj files (just ProjectName.csproj). 

Here's the output of doctor. 

https://gist.github.com/kdrzymala/718a161b170745d023cd736ea81a9388

It's taking ages on step 'parsing RopeRunnerUnity' (same for gen command).
Using Unity 2018.2.4.

I had it working fine on my other machine (it was using Assembly-CSharp.csproj there)

Any ideas? Is there anything I missed?

**Comment by sschmid** [comment]
To identify the issue, please tun `jenny gen -v`
When the logs are printed, is there some point where it takes a long time waiting? If so, where?

**Comment by kdrzymala** [comment]
Yep, I did that. It gets stuck at the parsing step.
Here's the output:
https://gist.github.com/kdrzymala/e947c30eebdc9c3c2d9e84c359aeed99

**Comment by sschmid** [comment]
Ok, so here:

```
Opened RopeRunnerUnity
Parsing RopeRunnerUnity

<------ Takes long time here?


Complete RopeRunnerUnity
```

**Comment by kdrzymala** [comment]
Yes, that's right! :)

**Comment by kdrzymala** [comment]
I've tested it on some other machines and I noticed that each time Unity generates ProjectName.csproj this bugs happens. Didn't notice it when I had AssemblyCSharp.csproj

Is there any rule why Unity generates one over the other?

**Comment by nbreum15** [comment]
I had this issue when I deleted the `Generated/` folder and it was stuck at `Parsing Project`. I simply deleted all the `Generated/` entries in the .csproj and everything worked smoothly again.
