### ISSUE TITLE
KeyNotFoundException when generating source code using Jenny.

### ISSUE THREAD

**Issue by gd2020** [sschmid/Entitas#784]
Hi All
I suggest sth.. I found out sth which causes KeyNotFoundException.
I'm pretty sure you all already know it.
It must be before a user hasn't generated code from Entitas yet. (or not be imported plugin)
I wanted to modify to let it print 'Please generate code using Entitas' or execute this process,
but it seems like DesperateDevs is not part of this project.

**Comment by sschmid** [comment]
Hi,

indeed, I've seen this too :D This error message might be confusing, you are right.
DesperateDevs is not part of the Entitas project, I will take a look into this.

Fyi:
KeyNotFoundException is usually thrown by the Properties.cs class, which is thrown, when a key is requested that doesn't exists, e.g. when the Preferences.properties is not yet configured
