### ISSUE TITLE
What would happen if I have 1000 component type?

### ISSUE THREAD

**Issue by zsydeepsky** [sschmid/Entitas#785]
Hi,

I have a question.

I saw in the base class, Entity has a **IComponent[]** array which has the exact length of the total component classes count

so what would happen if I made a lot of component types (like 1000), would it impact the performance badly?

Thanks

**Comment by StormRene** [comment]
Not really. We currently have a total of 1.7k components in our project with 800 in the largest context. So far we don't have any problems.

**Comment by sschmid** [comment]
@zsydeepsky it would affect the memory footprint per entity, but not really the runtime performance. Entities will be reused, so once created you won't allocate the array again and again. If you want to know the exact numbers, you can can calculate numComponents * sizeOf ref to get the memory consumption of the component arrays

**Comment by zsydeepsky** [comment]
OK, thanks for the answers guys :)

**Comment by zsydeepsky** [comment]
> Not really. We currently have a total of 1.7k components in our project with 800 in the largest context. So far we don't have any problems.

just for curiosity
is your project targeted on mobile? especially on some old phone models like iPhone 6?

**Comment by StormRene** [comment]
Yes, we support the current version up to iPhone 6, but we also plan to support 5s.

**Comment by zsydeepsky** [comment]
> Yes, we support the current version up to iPhone 6, but we also plan to support 5s.

Cool~
I have no problems then
Thanks for your info~

**Comment by StormRene** [comment]
You are welcome pal

**Comment by optimisez** [comment]
@StormRene How many system u have? Are remain all the systems together all the time or u load different set of systems based on scene?

**Comment by StormRene** [comment]
@optimisez Around 3,5k systems. Mostly reactive. Yes they all stay together all the time - loaded on start of app.

**Comment by sschmid** [comment]
@StormRene do try to keep the parent systems as flat as possible to reduce method calls, or are you clean with tons of sub parent systems?

**Comment by StormRene** [comment]
tons of sub parent systems :-D

**Comment by optimisez** [comment]
@StormRene Awesome. What's the target frame rate of your game? 60 fps?

**Comment by StormRene** [comment]
We create a city builder game with tower defense elements so 30 fps is enough. More is nice to have.

**Comment by optimisez** [comment]
@StormRene I see. Thanks for sharing your experience.

**Comment by sudall** [comment]
@StormRene out of curiosity, what does you folder structure and organization strategy look like for components and systems? I imagine with that many components/systems organization is critical since you might forget what a component/system is for eventually and therefore forget where to go to update something or accidentally create another component type that is meant for the same purpose as a component that already exists, for example.

**Comment by StormRene** [comment]
The structure looks like the following:
->Client
-->UIFeatures
-->ActionFeatures
-->InputFeatures
-->Services
-->Factories
->Simulation
-->CoreFeatures
--->DayFeature
---->MorningFeature
----->MorningComponent
----->SomeMorningSystems...
-->MetaFeatures
-->CommandFeatues
-->Services
-->Factories

 Folder == Feature - Each folder needs a feature class.
Of course it happens that logic is written twice, or it is forgotten that there are already components. I assume this happens with every big software project. Communication and documentation is the key.

**Comment by sudall** [comment]
True that. Cool, thank you for sharing. Organization with ECS architecture is something I've been struggling with.
