### ISSUE TITLE
EntitasEnumGenerator

### ISSUE THREAD

**Issue by roygear** [sschmid/Entitas#791]
# Install

This generator made for Roslyn version only. 

Copy the DLLs in below zip to the folder Jenny.
And only copy `Gear.Roslyn.CodeGeneration.Attributes.dll` to Unity's Assets folder .
[Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumGenerator20180926v2.zip](https://github.com/sschmid/Entitas-CSharp/files/2418947/Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumGenerator20180926v2.zip)

Run ```Jenny.exe auto-import -s ``` as usual.

Below contents will be added to the ```Preferences``` file.
```
Jenny.Plugins = Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumGenerator
Jenny.DataProviders = Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumDataProvider, \
                      Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumItemDataProvider
Jenny.CodeGenerators = Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumGenerator
					  
```

# Usage 

```CSharp
//We define a enum
public enum State
{
    Attack,
    Defend
}
```

## 1. Unique 
The enum is unique in the context. We use it like: 

```CSharp
        contexts.game.ReplaceState(State.Attack);
        contexts.game.ReplaceState(State.Defend);
```

```CSharp
//Define our component
using Entitas;
using Entitas.CodeGeneration.Attributes;
using Gear.Roslyn.CodeGeneration.Attributes;

[Game]
[Unique] 
[EntitasEnum]
public sealed class StateComponent : IComponent 
{
    public State value;
}
```

## 2. Sharable
This enum could be sharable.

```CSharp
var e = contexts.game.CreateEntity();

e.ReplacePlayerState(State.Attack);
e.ReplacePlayerState(State.Defend);

e.ReplaceEnemyState(State.Attack);
e.ReplaceEnemyState(State.Defend);

```

```CSharp
//define our codes
using Entitas;
using Gear.Roslyn.CodeGeneration.Attributes;

[Game]
[EntitasEnum]
public sealed class PlayerStateComponent : IComponent
{
    public State value;
}

[Game]
[EntitasEnum]
public sealed class EnemyStateComponent : IComponent
{
    public State value;
}
```

### _Will generate_ : 
_**1. Component of enum item**_
eg.
we define `StateComponent`, we will have:
`StateAttackComponent`
`StateDefendComponent`

**_2. ReactiveSystem_**
```CSharp
// example of StateComponent
// Any systems react to `State` should execute after this system.
public sealed class GameStateSystem : ReactiveSystem<GameEntity>
{
    public GameStateSystem(Contexts contexts) : base(contexts.game) { }

    protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context){
        return context.CreateCollector(GameMatcher.State);
    }

    protected override bool Filter(GameEntity entity) {
        return entity.hasState;
    }

    protected override void Execute(List<GameEntity> entities){
        foreach (var e in entities){
            e.ChangeStateTo(e.state.value);
        }
    }
}
```

**_3. Extension_**
```CSharp
// example of StateComponent
public static class GameStateEnumExtension
{
    public static void ChangeStateTo(this GameEntity entity, State newValue)
    {
        switch (newValue){
            
            case State.Attack:
                entity.isStateDefend = false;
		entity.isStateAttack = true; // the target case always at the bottom
                break;
            
            case State.Defend:
                entity.isStateAttack = false;
                entity.isStateDefend = true; // the target case always at the bottom
                break;
        }
    }
}
```

## 3. Combine with EventSystem

```CSharp
//define our codes
[Game]
[EntitasEnum]
[Event(EventTarget.Self, EventType.Added)]
[Event(EventTarget.Any, EventType.Removed)]
public sealed class PlayerStateComponent : IComponent
{
    public State value;
}
```

All contents of `EventSystem` on `PlayerStateComponent` will also apply to 
```
PlayerStateAttackComponent
PlayerStateDefendComponent
```

## 4. EntitasEnumAffix
For different needs, `EntitasEnum` Attribute use a enum `EntitasEnumAffix` to define what content will be generated.

```CSharp
[EntitasEnum(EntitasEnumAffix.Full)] // will generate the ReactiveSystem, extension and components of enum items
[EntitasEnum(EntitasEnumAffix.ExtensionAndComponent)] //  generate extension and  components of enum items
[EntitasEnum(EntitasEnumAffix.Component)] // only generate components of enum items


[EntitasEnum] //default is full
public sealed class PlayerStateComponent : IComponent
```

#

**Comment by CCludts** [comment]
Awesome! Happy to see members from the community sharing code 👍 

Small suggestion: in `ChangeStateTo` it might be cleaner to first remove all components before adding new components. This avoids issues when using groupevents such as OnEntityAdded.

```
                entity.isStateDefend = false;
                entity.isStateAttack = true;
```

**Comment by roygear** [comment]
Thanks for suggestion!
Please check the updated file.

**Comment by jrmacgill** [comment]
`Could not load file or assembly 'file:///C:\Users\jmacg\Documents\Unity\TCG\Jenny\Plugins\Gear\Gear.Roslyn.CodeGeneration.Plugins.EntitasEnumGenerator.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)` :(

**Comment by roygear** [comment]
@jrmacgill 
Which version of Entitas you are using?
Would you mind show your Preferences file?

**Comment by jrmacgill** [comment]
Same error... However, did some searching for the error and found that windows was blocking your DLLs.  Right click, properties, (this DLL came from another computer... unblock [ ]) on all three DLLs and the problem is fixed.

**Comment by jrmacgill** [comment]
Why do 'shared' versions not create Extensions?  It would be nice to use ReplaceX in both cases no?

**Comment by roygear** [comment]
Currently, I have different usage for `Sharable` case. I will update usage section later because it related to my another generator.

Of course, the `Replace()` style is doable. I may create a parameter to define what function can be generated depending on different needs.
