### ISSUE TITLE
Can't not generate code with Unity2018.2.7f1

### ISSUE THREAD

**Issue by LukeChen** [sschmid/Entitas#798]
Hi,

I found a bug

Can't not generate code with Unity2018.2.7f1 . 

using Entitas;
[Game]
public class HealthComponent : IComponent
{
    public float value;
}

**Comment by StormRene** [comment]
Hello in the community. Unfortunately you have to give us more information about your bug. The code you showed is not very revealing. Please use the formatting for code for the next time.

**Comment by sschmid** [comment]
@LukeChen The code generator should still. Can you show your Preferences.properties file. You will find this file in the project folder on the same level as the Assets folder.

Also make sure that in the Unity Player Settings you chose .NET 4.x

**Comment by sschmid** [comment]
Here's a link with common pitfalls. Please check and see if that helps
https://github.com/sschmid/Entitas-CSharp/issues/803#issuecomment-427126471
