### ISSUE TITLE
I have a problem how can I reuse Jenny?

### ISSUE THREAD

**Issue by TimeToTheNorth** [sschmid/Entitas#841]
![3_ qu f04i 8h_f4k 3e](https://user-images.githubusercontent.com/45864431/49979764-78619c00-ff8b-11e8-9910-66cb03c5d248.png)

**Comment by sschmid** [comment]
I'm not sure, so I'm guessing: does it work if you have only english letters in the path name?

**Comment by TimeToTheNorth** [comment]
Every time I need to go to the self-selection configuration！ So Jenny doesn't have a default address？

**Comment by TimeToTheNorth** [comment]
I am a beginner many things do not understand， hope to forgive

**Comment by sschmid** [comment]
Default is `./Jenny.properties` in the root of your project folder
