### ISSUE TITLE
I Can't use jenny server

### ISSUE THREAD

**Issue by meichen8050753** [sschmid/Entitas#842]
Hi,

I have an exception when I use jenny server in Mac

Here's Exception

Server is listening on port 3333...
gen
Generating using /Users/mc.0/Documents/ClientProjectA/UnityClient_ECS/Preferences.properties
Could not load type of field 'Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection:_handle' (0) due to: Could not load file or assembly 'SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535' or one of its dependencies.
Cheers

**Comment by sschmid** [comment]
Hi, just to narrow down possible, could you just run `Jenny/Jenny.exe`, this will start teh Jenny Wizard. Could you test and create a new Jenny.properties with the Jenny wizard and do auto import everything automatically? Maybe that helps

**Comment by koden-km** [comment]
This sounds like the same issue i'm getting in #811 (the recent post). People have worked around it by downgrading Mono to 5.14.

**Comment by meichen8050753** [comment]
> This sounds like the same issue i'm getting in #811 (the recent post). People have worked around it by downgrading Mono to 5.14.

Thanks, It's usefull

**Comment by meichen8050753** [comment]
> Hi, just to narrow down possible, could you just run `Jenny/Jenny.exe`, this will start the Jenny Wizard. Could you test and create a new Jenny.properties with the Jenny wizard and do auto import everything automatically? Maybe that helps

when I use Jenny wizard, There are the same error.

**Comment by sschmid** [comment]
Has been fixed! Will close
