### ISSUE TITLE
What is the proper way to generate Jenny.properties?

### ISSUE THREAD

**Issue by Jennal** [sschmid/Entitas#847]
Hi,

I am using 1.12.1, downloaded from Asset Store.

And I found that there are 2 ways of generate Jenny.properties:

1. Generate from command line
2. Generate from Unity GUI

But the 2 ways generated different contents, especially the `Jenny.SearchPaths`. What is the proper way to generate? And I can't use the GUI version to start Jenny-Server.

**Comment by sschmid** [comment]
@Jennal both ways are fine. When you use jenny wizard (run Jenny.exe without any parameters) with the command line, it performs some additional cleanup logic which might explain the difference in the searchPaths. 

Personally, it create a new Jenny.properties with `jenny new` and then I specify the initial search path where the auto-import command should search for plugins
```
Jenny.SearchPaths = Jenny/Plugins
```

now I just start the jenny wizard and follow the instructions
