### ISSUE TITLE
Cannot run `Jenny.exe gen` on pure C# project

### ISSUE THREAD

**Issue by charlieamer** [sschmid/Entitas#851]
Hi,

I tried to use Roslyn compiler on my new C# pure project, and I wasn't able to run `Jenny.exe gen` (i've got properly configured Jenny.properties file, as well as properly configured .csproj). I also couldn't run it using the [tutorial](https://github.com/sschmid/Entitas-CSharp/wiki/Entitas-pure-C%23) that was provided for Entitas Pure. (so in order to reproduce the issue, just follow the tutorial on a Windows machine. Instead of `mono Jenny.exe` simply use `Jenny.exe`).

I got Jenny.zip today from Unity asset store. The version is 1.12.2.

The error that pops in the terminal is:
`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

I managed to run `Jenny.exe gen` as a debug target in visual studio, to extract LoaderExceptions property, and here are the details ![LoaderExceptions details](https://files.gitter.im/sschmid/Entitas-CSharp/SMsf/image.png)

I am trying to do this on Windows 10 machine.

EDIT: If I try to follow the tutorial, but don't enable roslyn plugin when asked, `Jenny.exe gen` runs without a problem.

**Comment by sschmid** [comment]
@charlieamer if you're on windows you can run Jenny.exe directly. You only need to use mono if you're on macOS.

You can append `-v` to any command to get verbose output
e.g.
```
./Jenny/Jenny.exe gen -v
```

**Comment by sschmid** [comment]
when you run Jenny.exe without any parameters it will start the jenny wizard which helps you generate a proper Jenny.properties file. Usually that helps when there are any issues

**Comment by charlieamer** [comment]
@sschmid After installing **Mono for Windows** I have managed to get it to work (after a bit of hacking).

First when I installed it and run `mono ..\Jenny\Jenny.exe` on my project, after i selected which plugins I want, I was presented with the following error:
`Could not load type of field 'Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection:_handle' (0) due to: Could not load file or assembly 'SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535' or one of its dependencies.`

**The solution** was a bit boring, I had to install the package "SQLitePCLRaw.core" in a dummy c# project, went to package files and found a `SQLitePCLRaw.core.dll` file, and copied the file to the same directory as where `Jenny.exe` resides. That made it work and it finally works like a charm (for `mono ..\Jenny\Jenny.exe`).

My advice: you should pack `Jenny.zip` with `SQLitePCLRaw.core.dll` pre-packaged, so that it works out of the box for third-party installed mono. You should also look into the error I mentioned above for default .NET support on windows, and see why exactly it fails, and can it be fixed. I don't think I should close the issue as this wasn't solved for me without using mono (I wasn't able to run `Jenny.exe gen` even after I copied `SQLitePCLRaw.core.dll` to Jenny directory, I still got the same error as mentioned above).

**Comment by AstralRoad** [comment]
follow @charlieamer , I use mono to run jenny.exe and modify Entitas.CodeGeneration.Plugins.Assemblies = **Library/ScriptAssemblies/Assembly-CSharp.dll**
to project dll path in bin/Debug/{.netversion}/{dllname}.dll
it works for me

**Comment by sschmid** [comment]
@charlieamer 

EntitasPure has been renamed to Entitas-Standalone and is updated to .NET 6.0 and using nuget.
You can now generate using dotnet. Please see: [Entitas-Standalone](https://github.com/sschmid/Entitas-Standalone)
