### ISSUE TITLE
Api Suggestion

### ISSUE THREAD

**Issue by iliaga** [sschmid/Entitas#855]
Hi,

I have an idea : make the CreateComponentWhatever api to return entity so we could construct entities with a fluent api.
example :

```csharp
using Entitas;

public sealed class MyComponent : IInitializeSystem
{

    void Initialize()
    {
        createEntity().AddT1(param,param).AddT2(param);
    }

}
```

Cheers

**Comment by sschmid** [comment]
Fluent Api for components will come back! :)

**Comment by sschmid** [comment]
Fluent api will definitely come back. Working on it, see new code generator #1005
