### ISSUE TITLE
Add support for .shproj projects in Jenny

### ISSUE THREAD

**Issue by charlieamer** [sschmid/Entitas#856]
Hi,

I have a suggestion. Would it be possible to add support for Shared Projects (`.shproj` extension) in Jenny ? Right now, when I do `mono ..\Jenny\Jenny.exe gen` I am presented with an error `One or more errors occurred. (Cannot open project 'PiratesRising.shproj' because the file extension '.shproj' is not associated with a language.)`

.shproj files are just shared C# files, they don't have a target framework and cannot have external dependencies, so it is just a pure C# code. `.shproj` files seem to have same very similar structure as `.csproj` files, I believe support is already there, it just has to be enabled.

One way to go around this issue is to rename `.shproj` file to `.csproj` file, then run Jenny, and after that rename file back to `.shproj`.

The other way (which I am using) is to make a symbolic link file named `YourProject.csproj` that links to `YourProject.shproj`.

At the moment I didn't find any problems with this.

Cheers

**Comment by hiradyazdan** [comment]
@charlieamer can you generate your components correctly using this?

**Comment by sschmid** [comment]
Hi, sorry for not replying earlier. Happy your workaround with symbolic links works.
Jenny itself just uses Roslyn and only supported projects work.
I will close.

Fyi, I started working on a Jenny replacement using dotnet's source generators. See #1005
