### ISSUE TITLE
State Machine as a service

### ISSUE THREAD

**Issue by fraylopez** [sschmid/Entitas#860]
Hi,

I have been thinking about the implementation of state machines within Entitas and ECS in general. Since it's a recurrent topic I'm going to write it down hoping to hear some thoughts from the community.

I'm going to start by stating the obvious: the State Machine pattern is purely OOP and cannot be ported directly to ECS. The motivation of this approach is my own incapacity to solve certain problems in ECS since my mindset is used to classic OOP, I am sure that exprienced ECS devs will find better ways to achieve the same.

The idea is to build ONLY the state machine "graph" using the preferred method and then use Entitas to store the current state into components and wire up the logic into systems.

I'm going to write some code for clarity starting with the OOP state machine. It will receive events through `IStateMachine.On ` and return the next state. The state will have some transitions, identifiers and so on, the actual implementation isn't important, it just represents the graph and does not includes any game logic.

```csharp

public interface IStateMachine {
    IState On(IEvent e);
}

public interface IState
{
    string Id { get;}
    IEnumerable<ITransition> Transitions { get;}
}

public interface ITransition
{
    IState TargetState { get;}
    IState On(IState from, IEvent e);
}
```

The main system will rely on 2 components. The `StateComponent` and the `EventComponent` attached to a unique state entity.

```csharp
using Entitas;

[GameState, Unique]
public class StateComponent : IComponent
{
    public IState current;
}

[GameState, Unique]
public class EventComponent : IComponent
{
    public IEvent value;
}

```

The state machine can be implemented in pure csharp, Unity scriptable objects, mecanim or any other.
Then using the same approach that is used a lot in Entitas, for example in view services, expose the state machine somehow to be accessed within the systems. Let's say `Services.StateMachineService`.

Then the core system to handle the state change will look like the following.

```csharp
using Entitas;
using System.Collections.Generic;

public class ChangeStateSystem : ReactiveSystem<GameStateEntity>
{
    private readonly Services services;

    public ChangeStateSystem(Contexts contexts, Services services): base(contexts.gameState)
    {
        this.services = services;
    }

    protected override bool Filter(GameStateEntity entity)
    {
        return entity.hasEvent;
    }

    protected override ICollector<GameStateEntity> GetTrigger(IContext<GameStateEntity> context)
    {
        return context.CreateCollector(GameStateMatcher.Event);
    }

    protected override void Execute(List<GameStateEntity> entities)
    {
         foreach (var e in entities)
        {
            var nextState = services.StateMachine.On(e.event.value);
            e.ReplaceState(nextState );
        }
    }
}

```

Now, the current state logic can be declared into a system. 

```csharp
using System.Collections.Generic;
using Entitas;

public class StartLevelSystem : ReactiveSystem<GameStateEntity> 
{
    public StartLevelSystem(Contexts contexts) : base(contexts.gameState)
    {
    }

    protected override bool Filter(GameStateEntity entity)
    {
        return entity.hasState && entity.state.current.Equals(GameStates.PlayLevel);
    }

    protected override ICollector<GameStateEntity> GetTrigger(IContext<GameStateEntity> context)
    {
        return context.CreateCollector(GameStateMatcher.State);
    }

    protected override void Execute(List<GameStateEntity> entities)
    {
        foreach (var e in entities)
        {
            //start level code
        }
    }
}
```

That's pretty much it! I have used it in a test project I am doing to learn Entitas and I am pretty happy with it. Do you see any downsides and/or interesting mods?

**Comment by vanlecs09** [comment]
This is my implementation of FMS (game state manager )
 
public static class GameStateContextExtension
{
    public static void ChangeToGameState(this GameStateContext gameStateContext, GAME_STATE newGameState, string assetName)
    {
        var entity = gameStateContext.CreateEntity();
        entity.AddGameStateEnter(assetName, newGameState);
        entity.isGameStateUpdate = false;
        entity.isGameStateExit = false;
    }
}

- EnterState
public class GameStateEnterSystem : ReactiveSystem<GameStateEntity>, IInitializeSystem
{
    GameStateService _gameStateService;
    Contexts _contexts;

    public GameStateEnterSystem(Contexts contexts) : base(contexts.gameState)
    {
        _contexts = contexts;
    }

    protected override bool Filter(GameStateEntity entity)
    {
        return entity.hasGameStateEnter;
    }

    public void Initialize()
    {
        _gameStateService = (GameStateService)_contexts.meta.gameStateService.instance;
    }

    protected override ICollector<GameStateEntity> GetTrigger(IContext<GameStateEntity> context)
    {
        return context.CreateCollector(GameStateMatcher.GameStateEnter);
    }

    protected override void Execute(List<GameStateEntity> entities)
    {
        foreach (var e in entities)
        {
            var uiEntity = _contexts.uI.CreateEntity();
            uiEntity.AddAsset(e.gameStateEnter.assetName);
            e.isGameStateUpdate = true;
        }
    }
}

- UpdateState

public class GameStateUpdateSystem : IExecuteSystem, IInitializeSystem
{
     GameStateService _gameStateService;
     Contexts _contexts;

    public GameStateUpdateSystem(Contexts contexts)
    {
        // this._gameStateService = contexts.sta;
        _contexts = contexts;
    }

    public void Initialize()
    {
        _gameStateService = (GameStateService)_contexts.meta.gameStateService.instance;
    }
    
    public void Execute()
    {
        // _gameStateService.Update();
    }
}

ExitState

public class GameStateExitSystem : ReactiveSystem<GameStateEntity>, IInitializeSystem
{
    GameStateService _gameStateService;
    Contexts _contexts;

    public GameStateExitSystem(Contexts contexts) : base(contexts.gameState)
    {
        _contexts = contexts;
    }

    protected override bool Filter(GameStateEntity entity)
    {
        return entity.hasGameStateTransition;
    }

    public void Initialize()
    {
        _gameStateService = (GameStateService)_contexts.meta.gameStateService.instance;
    }

    protected override ICollector<GameStateEntity> GetTrigger(IContext<GameStateEntity> context)
    {
        return context.CreateCollector(GameStateMatcher.GameStateExit);
    }

    protected override void Execute(List<GameStateEntity> entities)
    {
        foreach (var e in entities)
        {
            // e.isGameStateUpdate = true;
            // destroy view
        }
    }
}

public enum GAME_STATE {
    MENU, 
    GAME_PLAY
}


How to change state to state 
_gameStateContext.ChangeToGameState(GAME_STATE.MENU, "Assets/Game/Prefabs/pref_ui_menu");

**Comment by akoolenbourke** [comment]
Hi @fraylopez, did you continue work on this system and how has it worked out? I have a couple of questions (I'm new to Entitas and Unity)

By putting [Unique] on the components, you're only ever going to get one entity with those components right? If so, there's no need for the foreach loop correct?

I also see you get StateMachine from services. Does this mean this system only works with one state machine and would not work in general for statemachines for other objects in the game

**Comment by fraylopez** [comment]
Hi @akoolenbourke, 
I'm quite happy with the result, it served it's purpose and scaled up quite well, the current version is a bit more complex than the one I write down here.

Regarding your first question, yes, looping interfaces when using unique components is a bit redundant but that way my code implementation is not dependent on a "meta" tag in another file which eventually may change and I don't have to think about it while coding. Keep in mind that Entitas will always emit a entity list as argument for Execute method, even with a single member.

Regarding your second question, the idea of this snippet is Game State handling through a state machine. The game state is assumed to be unique, and the service strategy is just a way to expose "state change triggers" to the code in a clean way. However, the pattern is useful without the "service" exposure. 
In my Entitas test project I use it also on a smaller system state machine that builds the levels of a grid-based puzzle game in a concrete order (board-layer, obstacle-layer, piece-layer,...). 

Hope it helped!

**Comment by akoolenbourke** [comment]
Great, thanks!

**Comment by DrebotArtem** [comment]
@fraylopez Hi! I ran into a few difficulties. I created a StateMachineService, but I couldn't combine States and Transitions. Can you show an example of how you create states and transitions?

**Comment by sschmid** [comment]
Hi, I have never used state machines with Entitas, so my feedback might not be that helpful. I consider each unique component a state which lets me compose states and systems to their thing based on that. No further abstraction needed.
