### ISSUE TITLE
UPM specific GIT repo

### ISSUE THREAD

**Issue by mchamplain** [sschmid/Entitas#862]
Hi,
with Unity 2018.3 supporting git repo in the package manager, any chance to have a compatible repo for Entitas?

More info: https://forum.unity.com/threads/git-support-on-package-manager.573673/

Goal: Be able to easily keep Entitas outside of the Assets folder by simply adding a reference to the git repo in the manifest.json file.

Nice to have: a private git repo for those who bought with Jenny

**Comment by sschmid** [comment]
Sounds great! I will check it out in the future!
Thanks for the suggestion

**Comment by sschmid** [comment]
Will do using openupm, see #992
