### ISSUE TITLE
What Platforms does Entitas work on?

### ISSUE THREAD

**Issue by akoolenbourke** [sschmid/Entitas#873]
Hi there.

Just wondering what platforms Entitas is supported on. We're looking for a solution that supports all current platforms....Mac, Windows, tvOS, iOS, consoles etc

Thanks

**Comment by sschmid** [comment]
Hi,
Entitas is plain c# and there are no known limitation for those platforms.
If you use Unity for example, it should be easy to deploy you application on all those platforms.

**Comment by akoolenbourke** [comment]
Thanks Simon. May I also say great work on Entitas, it's looking very good to me so far. We're about to embark on a project (Commercial, many platforms) so hopefully it can handle what we need.

Another quick question that I haven't been able to find an answer to yet, is do you see any issues with Entitas and multiscene loading? We will be using a boot scene that then manages sub scenes, creating and destroying objects (And hence Entities) on level start and destroying on level end, repeating this process etc.

Any best practices here? Like keep all systems global for the entire program life in the boot scene, or add and remove Systems/Features as required?

Thanks

**Comment by StormRene** [comment]
I don't see a problem with multiscene loading. We are doing the same of course. Using as startup scene and loading different scenes depending on the needs. 
If you built your systems reactive you don't need to enable/disable them. They can stay all the time enabled indipendent which scenes are loaded or not.

**Comment by FNGgames** [comment]
I use mutliple scenes with a single core scene as you describe. No problems with this and entitas. I do all my scene management in ECS, storing the state as components and issuing commands as other components (e.g. ActiveSceneComponent and LoadSceneComponent respectively)
