### ISSUE TITLE
[Bug] Hard Crash - Selecting linked entities in editor locks up and crashes Unity

### ISSUE THREAD

**Issue by jedh** [sschmid/Entitas#875]
Whenever you select a linked entity in the editor when the game is running Unity locks up and then crashes. This happens whether the game is playing or paused. If you un-link the entity you can select it without crash, however, you are unable to view it's components and current state. This is happening with Unity 2018.3.8f1 using the purchased version of Entitas from the Asset Store. If it helps, Roslyn was used for code generation.

**Comment by sschmid** [comment]
Hi,
I just double checked selecting linked entities and it worked.
Maybe it's a different problem:
When Entitas draws components with custom types as fields and it when it doesn't find a custom ITypeDrawer for that type, it tries to draw them using reflection. For works for most of the types but for  some complex types that might not work properly and Unity might hang or crash.
If you encounter such a type you can either implement a custom ITypeDrawer or use the [DontDrawComponent] attribute on the component class.

Could you double check if that causes the issue?
