### ISSUE TITLE
How do I fully teardown/shutdown Entitas and getting rid of DebugSystemsBehaviour

### ISSUE THREAD

**Issue by huhund** [sschmid/Entitas#923]
What would be the correct way of fully removing all Entitas items from the scene? Currently I do like this:

`
m_systems.TearDown();
m_systems.DeactivateReactiveSystems();
Contexts.sharedInstance.Reset();
m_systems = null;
`

But e.g. DebugSystemsBehaviour objects are still persistent in the Unity scene. How can I get rid of those. When I init new systems I get duplicate debug objects.

Best, Hu

**Comment by sschmid** [comment]
Hi!
There's no api for that yet, but you can GameObject.Find() the DebugSystemsBehaviour and destroy it manually.
If there are no issues you can probably ignore that. It's a Unity Editor thing only. In production builds this will be stripped out and there is no DebugSystemsBehaviour. So it only affects you when developing in Unity.
