### ISSUE TITLE
Any Paid or Free Video Tutorial

### ISSUE THREAD

**Issue by vishyvishy** [sschmid/Entitas#930]
Friends,

I have bought Entities.
But I am not able to understand much from github source pages

Is there any free or Paid video tutorial available that teaches how to use Entitas to create games?
I did not find anything on Udemy or skillshare.

**Youtube Desperate Dev videos are going way over the head ..**.

Please guide me in this.

I really wish there were some free or paid course in Entitas, so that one can digest this entity component system methods slowly, surely and, completely 

Thanks

**Comment by mchamplain** [comment]
this one looks pretty good. it's using v0.45 but there hasn't been much changes in the general concepts since then, I think it should help you understand the framework.

**Comment by sschmid** [comment]
I hope these will help

Entitas ECS Unity Tutorial - Setup & Basics
https://www.youtube.com/watch?v=L-18XRTarOM

Entitas - Entity System Architecture with Unity - Unite Europe 2015
https://www.youtube.com/watch?v=Re5kGtxTW6E

Introduction to Entitas
https://www.youtube.com/watch?v=0wodRUOoHKg&list=PL4pK6pSyCCvS3rLYUvm9_MQYX6QNkSc4a

https://www.youtube.com/watch?v=1qh6fTHeb5E
2018.02.18 Entitas + Asteroids workshop
