### ISSUE TITLE
Show class short name for components in the hierarchy

### ISSUE THREAD

**Issue by OmiCron07** [sschmid/Entitas#945]
![image](https://user-images.githubusercontent.com/31325575/90674139-b3b77200-e226-11ea-8c91-7a4aa5c6cc5c.png)

It would be nice to show only the class name and not the full namespace in the component list of an entity in the hierarchy. With the short name, I would be able to see more components thant just the first one.

Same for console logs :

![image](https://user-images.githubusercontent.com/31325575/90675554-a3a09200-e228-11ea-8e8d-eb3e92b9a6bd.png)

**Comment by c0ffeeartc** [comment]
Can you make this value true in `jenny.properties` and see if it makes difference and doesn't break something else?
`Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true`

**Comment by OmiCron07** [comment]
It's already to true.

**Comment by c0ffeeartc** [comment]
Ok. So the problem is inside `Entity.ToString` it was changed in some commit to improve visual debugging performance.

You can move component outside namespace, or  modify `Entity.ToString` and recompile Entitas.dll

**Comment by WeslomPo** [comment]
I just adding ToString to all my components, sounds crude, but when you do it in new project - this is not a problem.

**Comment by sschmid** [comment]
Yes, you can override `ToString()` in the component to customize what's shown in the hierarchry
