### ISSUE TITLE
how do I create 2 separate "Context" ?

### ISSUE THREAD

**Issue by bayganik** [sschmid/Entitas#951]
Hi,

Thank you for sharing your software.  How do I create 2 separate "Context" to be able to create entities?
for example: I want my Game entities to be created separate from UI entities.

I tried different system and features but it won't work.

Cheers
Kamran

**Comment by WeslomPo** [comment]
Make separate contexts like GameContext and UiContext, no? You can make a different contexts in preferences.

**Comment by bayganik** [comment]
I use Entitas in csharp.  I do NOT use Unity.

**Comment by c0ffeeartc** [comment]
You should modify config file that generator reads from and add context name to `Entitas.CodeGeneration.Plugins.Contexts` see https://github.com/sschmid/Match-One/blob/master/Jenny.properties for example

**Comment by sschmid** [comment]
@bayganik 
See [Entitas-Standalone](https://github.com/sschmid/Entitas-Standalone)
It's a pure C# console app. Contexts can be defined in `Jenny.properties` by specifying a comma separated list of context names for `Entitas.CodeGeneration.Plugins.Contexts`
