### ISSUE TITLE
How to deal with "Enable Visual Debugging = true, but components is not showing in DontDestroyOnLoad"?

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas#963]
https://github.com/atkdefender/Pic/blob/main/pic20201124122017.jpg

**Comment by Dethrail** [comment]
@atkdefender

I think problem was because you had trouble when registering all context observers

Solution only one, get some report via adding log in catch section at `Contexts`  

e.g. ```} catch(System.Exception e) {Debug.LogError(e);}```

After u got a report you can handle problem

**Comment by sschmid** [comment]
related #967

**Comment by mrobaczyk** [comment]
After adding these Debug.LogErrors I'm getting the following exception:
```
UnityEngine.UnityException: get_isPlaying is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'SceneLoader' on game object 'SceneLoader'.
See "Script Serialization" page in the Unity Manual for further details.
```
