### ISSUE TITLE
How to setup the Roslyn code generator

### ISSUE THREAD

**Issue by matthiashermsen** [sschmid/Entitas#965]
Hi there,
I'm using the Asset store version and try to setup the Roslyn code generator. Things have changed since Simon's video on how to set it up

https://youtu.be/L-18XRTarOM?t=232

So after unzipping the Jenny.zip file I do this

- I run `mono Jenny/Jenny.exe`
- Select "Use Jenny.properties"
- Select ??????
- Run "Save and continue (auto import)"
- Start the server via `./Jenny-Server`
- Generate via `mono Jenny/Jenny.exe gen`

But what needs to be selected from the CLI dialog? By that I mean this dialog

![image](https://user-images.githubusercontent.com/47159597/100669903-5fac4580-335e-11eb-8721-3edd1f2a5e17.png)

I tried to select just everything but this is wrong and leads to errors #962  

The rest of my setup steps should be fine I think?

**Comment by Brainshack** [comment]
So I guess this means Entitas just isnt supported anymore? When Documentation on something this important is missing and nobody is answering here, its just not worthwhile using anymore I am afraid.
