### ISSUE TITLE
I use vs. If I add attribute[Game] then print "public", it links me to "PublicMemberInfoEntityExtension"(namespace Entitas). Is that sth I can do to avoid this?

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas#974]
I use vs.
If I add attribute[Game] then print "public", it links me to "PublicMemberInfoEntityExtension"(namespace Entitas).
Is that sth I can do to avoid this?

**Comment by sschmid** [comment]
Do you mean VS auto completion, like this

```
[Game]
publ       <---- start writing public results in 'PublicMemberInfoEntityExtension'?
```

is that what you mean?

If so, not sure if you can change that. I can recommend using templates for components though
