### ISSUE TITLE
Does entitas support multithreading ? 

### ISSUE THREAD

**Issue by genaray** [sschmid/Entitas#984]
Hi,

im looking for an well designed c# ecs which supports multithreading.
Its for my game server and i dont want to use unity itself as a server. 

So i found entitas and wanna know if it already supports multithreading somehow. 
Is there already a build in multithreading/jobs/scheduling system for entitas ? 

Cheers

**Comment by eddy1001-555** [comment]
[URL=https://runaway3d.com/]run 3[/URL]  I really like it but I haven't studied it as well as you

**Comment by eddy1001-555** [comment]
runaway3d.com/]run 3[/URL] I really like it but I haven't studied it as well as you

**Comment by sschmid** [comment]
@genaray The core of Entitas uses System.Collections.Generic and is not thread-safe in general.
However, within systems you can do multithreading, see
- [JobSystem.cs](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Systems/JobSystem.cs)
- [TestJobSystem](https://github.com/sschmid/Entitas-CSharp/blob/0d74adc91df1db25b1001679d989f1f3195af49c/Tests/Tests/Fixtures/Systems/TestJobSystem.cs)
