### ISSUE TITLE
Jenny Window does not open

### ISSUE THREAD

**Issue by zendorx** [sschmid/Entitas#989]
I have tested few projects. After I deleted it. But in new project Jenny somewhy looking for preferences in old project folder and do not opens.

![image](https://user-images.githubusercontent.com/909905/145676394-acaed761-2268-4af1-8f4c-1cf7eb4a259f.png)

**Comment by sschmid** [comment]
Ok, looks like it saves the path to the Jenny.properties in the EditorPrefs. Clearing the EditorPrefs with `EditorPrefs.DeleteAll ` should help

**Comment by sschmid** [comment]
Fixed in [Entitas 1.14.0](https://github.com/sschmid/Entitas/releases)
