### ISSUE TITLE
There is no observers , if deactivate "Reload domain" in Project Settings -> Editor

### ISSUE THREAD

**Issue by Sergan4ik** [sschmid/Entitas#999]
Hi,

I found a bug, when you replay game in editor without "Reload Domain" option , there is no context observers in DontDestroyOnLoad

Inspector, after reload domain (any change in code)
![image](https://user-images.githubusercontent.com/72492804/172925996-2acf1b38-5c24-4d6b-bc91-160d17cd1f6f.png)

Inspector, if code the same, but starts game once more time
![image](https://user-images.githubusercontent.com/72492804/172926180-37d840eb-5d49-4d04-8af7-4281a26328f9.png)

If create observers manually, entities is duping , and can't collapse observers in inspector
First time:
![image](https://user-images.githubusercontent.com/72492804/172926497-bd82ea64-f3e1-4c05-bc36-42e26903394a.png)
Second:
![image](https://user-images.githubusercontent.com/72492804/172926523-432b29fe-d7f2-44bc-9f92-46667264baca.png)
Third:
![image](https://user-images.githubusercontent.com/72492804/172926556-6e571607-de60-4d5d-948f-670b48b0693a.png)

etc

**Comment by DeusExMachina1993** [comment]
Resetting Context in Start Worked for me.

```
_contexts = Contexts.sharedInstance;
_contexts.Reset();
```

**Comment by sschmid** [comment]
potential duplicate #967

**Comment by eterlan** [comment]
The reason is because turn off"Reload domain" would not reset those static fields. 
Add this code somewhere should fix this problem. 
```C#
    [InitializeOnEnterPlayMode]
    public static void ReloadContext()
    {
        Contexts.sharedInstance = null;
    }
```
or @sschmid have time to modify generator generate this one in context. I would like to help but have no idea howto..
